-- Seed real AI Literacy content, with no fictional people, events or activity.
-- Run in an authenticated administrator context AFTER the migration. See docs/ht-campus-setup.md.
-- Idempotent: an existing pathway at this ID is left unchanged, including local edits.
do $seed$
begin
 if auth.uid() is null or ht_private.member_role() is distinct from 'admin' then
  raise exception 'Run the learning seed as an active HT administrator.';
 end if;
 if exists(select 1 from public.ht_courses where id='20000000-0000-4000-8000-000000000001') then
  raise notice 'AI Literacy pathway already exists; no changes made.';
  return;
 end if;
 perform public.ht_campus_command('saveCourse','{"id":"20000000-0000-4000-8000-000000000001","title":"AI Literacy: From Curiosity to Practice","description":"Build a thoughtful, practical approach to AI. Learn the fundamentals, write a useful prompt, and create a small project with human review.","category":"AI Literacy","status":"draft","image_url":null}'::jsonb);
 perform public.ht_campus_command('saveModule','{"id":"50000000-0000-4000-8000-000000000001","course_id":"20000000-0000-4000-8000-000000000001","title":"Understand what AI can—and cannot—do","position":1,"body":"Generative AI predicts useful patterns in language, images, and other information. A fluent answer can still be inaccurate or incomplete. Treat its output as a draft to evaluate, not as evidence.\n\nBefore using a tool for coursework, check your instructor’s policy. Keep private student information, passwords, and confidential documents out of unapproved tools. Verify factual claims using reliable original sources, and acknowledge AI assistance when required.\n\nPractice: ask an AI tool to explain a familiar concept. Identify one claim you would verify and name a source you could check.","resource_url":null,"question":"An AI answer sounds confident. What should you do before using a factual claim?","options":["Use it immediately because confidence means accuracy","Verify the claim against a reliable original source","Ask it to use a more academic tone"],"answer_index":1,"assignment_prompt":null}'::jsonb);
 perform public.ht_campus_command('saveModule','{"id":"50000000-0000-4000-8000-000000000002","course_id":"20000000-0000-4000-8000-000000000001","title":"Write a clear prompt and evaluate the result","position":2,"body":"A useful prompt explains the task, audience, context, and desired output. State what a good result must include and what information is missing.\n\nExample: “Help me draft a study plan for two biology chapters over five days. I have 45 minutes each day. Include retrieval practice and a way to check my understanding. Ask me about any missing requirements before planning.”\n\nReview the result for accuracy, bias, usefulness, and fit. Improve one instruction at a time. You remain responsible for deciding whether the final output meets the assignment requirements.","resource_url":null,"question":"Which prompt provides the clearest task and constraints?","options":["Make something impressive","Write a lot about studying","Draft a five-day study plan with 45 minutes per day and retrieval practice"],"answer_index":2,"assignment_prompt":null}'::jsonb);
 perform public.ht_campus_command('saveModule','{"id":"50000000-0000-4000-8000-000000000003","course_id":"20000000-0000-4000-8000-000000000001","title":"Create, reflect, and share your work","position":3,"body":"Choose a small, practical task: a study plan, a campus event brief, or a portfolio summary. Use an approved AI tool if available; you may also write the prompt and expected output yourself.\n\nYour submission will be reviewed for a clear purpose, specific instructions, evidence of evaluation, and your own reflection. A staff reviewer will return feedback or approve the work. Completion is recorded only after all knowledge checks and this review are complete.","resource_url":null,"question":null,"options":[],"answer_index":null,"assignment_prompt":"Submit: (1) your task and intended audience; (2) the prompt you wrote; (3) a short excerpt of the result or your expected result; (4) what you verified or changed; and (5) one limitation and how you addressed it. Do not include confidential information."}'::jsonb);
 perform public.ht_campus_command('saveCourse','{"id":"20000000-0000-4000-8000-000000000001","title":"AI Literacy: From Curiosity to Practice","description":"Build a thoughtful, practical approach to AI. Learn the fundamentals, write a useful prompt, and create a small project with human review.","category":"AI Literacy","status":"published","image_url":null}'::jsonb);
end $seed$;
