/* HT Hub build: bundle every space's data into hub/data/all.js and regenerate the hub shells from _shell.tpl.
   Run: node ht/build.mjs   (from the repo root or anywhere) */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url'; import { createHash } from 'node:crypto';
const HUB = path.join(path.dirname(fileURLToPath(import.meta.url)), 'hub');
global.window = global;
new Function(fs.readFileSync(path.join(HUB, 'data.js'), 'utf8'))();
const order = global.HT.order;
const parts = [], present = [];
for (const k of order) {
  const f = path.join(HUB, 'data', k + '.js');
  if (k === 'advancement') { present.push(k); continue; }             // lives in data.js
  if (!fs.existsSync(f)) { console.log('missing:', k); continue; }
  const src = fs.readFileSync(f, 'utf8');
  new Function(src)();
  if (!global.HT.spaces[k]) { console.log('file did not define HT.spaces.' + k); continue; }
  parts.push('/* ---- ' + k + ' ---- */\n' + src.trim() + '\n'); present.push(k);
}
fs.writeFileSync(path.join(HUB, 'data', 'all.js'), '/* The HT Hub, every space. Generated by ht/build.mjs, do not edit by hand. */\n' + parts.join('\n'));
const tpl = fs.readFileSync(path.join(HUB, '_shell.tpl'), 'utf8');
/* One content stamp for every /ht/ asset. The root service worker caches static assets
   cache-first keyed by full URL, so the stamp MUST change whenever these files change. */
const ROOT = path.join(HUB, '..');
const V = createHash('sha1')
  .update(fs.readFileSync(path.join(ROOT, 'ht.css')))
  .update(fs.readFileSync(path.join(HUB, 'ht.js')))
  .update(fs.readFileSync(path.join(HUB, 'data.js')))
  .update(fs.readFileSync(path.join(HUB, 'data', 'all.js')))
  .digest('hex').slice(0, 8);
const esc = v => String(v).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
function shell(key, title, desc, dir) {
  const next = encodeURIComponent('/ht/hub/' + (key === 'home' ? '' : key + '/'));
  const out = tpl.replace(/__KEY__/g, () => key).replace(/__TITLE__/g, () => esc(title)).replace(/__DESC__/g, () => esc(desc))
    .replace(/__NEXT__/g, () => next).replace(/__DATA__/g, () => '<script src="/ht/hub/data/all.js?v=' + V + '"></script>')
    .replace(/__V__/g, () => V);
  fs.mkdirSync(dir, { recursive: true }); fs.writeFileSync(path.join(dir, 'index.html'), out);
}
/* the two hand-written pages carry the same stamp */
function stampPage(file) {
  if (!fs.existsSync(file)) return;
  let t = fs.readFileSync(file, 'utf8');
  const before = t;
  t = t.replace(/(["'])(\/ht\/[^"']+?)\?v=[A-Za-z0-9]+\1/g, (m, q, u) => q + u + '?v=' + V + q)
       .replace(/(["'])(\/ht\/(?:ht\.css|hub\/ht\.js|hub\/data\.js|hub\/data\/all\.js))\1/g, (m, q, u) => q + u + '?v=' + V + q);
  if (t !== before) { fs.writeFileSync(file, t); console.log('stamped', path.relative(ROOT, file)); }
}
shell('home', 'Home', global.HT.home.sub || '', HUB);
for (const k of present) { const s = global.HT.spaces[k]; shell(k, s.title, s.sub || s.blurb || '', path.join(HUB, k)); }
stampPage(path.join(ROOT, 'index.html'));
stampPage(path.join(ROOT, 'fund', 'index.html'));
console.log('all.js:', Math.round(fs.statSync(path.join(HUB, 'data', 'all.js')).size / 1024) + 'KB', '| stamp:', V, '| spaces:', present.join(', '));
