import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();let checks=0;
const eq=(a,b,msg)=>{assert.deepEqual(a,b,msg);console.log(`ok ${++checks} - ${msg}`);};
const reject=async(fn,re,msg)=>{await assert.rejects(fn,re,msg);console.log(`ok ${++checks} - ${msg}`);};
const sql=path=>readFile(new URL('../../'+path,import.meta.url),'utf8');
await db.exec("create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth,public to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;");
await db.exec(await sql('supabase/migrations/20260921180637_ht_campus_hub.sql'));
await db.exec(await readFile(new URL('classroom-legacy-bootstrap.sql',import.meta.url),'utf8'));
async function legacyFunction(file,name){const source=await sql('supabase/migrations/'+file),re=new RegExp('create (?:or replace )?function public\\.'+name+'\\(','i');const start=source.search(re);assert.ok(start>=0,name);const body=source.indexOf('$$',start),end=source.indexOf('$$;',body+2);await db.exec(source.slice(start,end+3));}
for(const [f,names] of [['0036_academy_room.sql',['ea_room_in_session']],['0037_ht_room.sql',['ea_room_is_host','ea_room_rotate_link','ea_room_set_hosts']],['0042_class_core.sql',['ea_class_can','ea_class_is_host']],['0054_ht_room_features.sql',['ea_room_reader','ea_room_state']],['0043_class_presence.sql',['ea_class_attendance_rows']],['0047_class_help.sql',['ea_class_help_queue','ea_class_help_may_ask']],['0049_class_warmups.sql',['ea_class_names']]])for(const name of names)await legacyFunction(f,name);
await db.exec(await sql('supabase/migrations/20260921193229_ht_cohort_classrooms.sql'));
await db.exec(await sql('supabase/migrations/20260921200136_ht_community_messages.sql'));
const oids=(await db.query("select 'public.ht_campus_command(text,jsonb)'::regprocedure::oid as command,'public.ht_campus_state()'::regprocedure::oid as state")).rows[0];
await db.exec(await sql('supabase/migrations/20260921221338_ht_native_coursework.sql'));
eq((await db.query("select 'public.ht_campus_command(text,jsonb)'::regprocedure::oid as command,'public.ht_campus_state()'::regprocedure::oid as state")).rows[0],oids,'coursework migration preserves public command and state OIDs');
const ids={student:'10000000-0000-4000-8000-000000000001',staff:'10000000-0000-4000-8000-000000000002',leadership:'10000000-0000-4000-8000-000000000003',other:'10000000-0000-4000-8000-000000000004',outsider:'10000000-0000-4000-8000-000000000005',admin:'10000000-0000-4000-8000-000000000006',instructor2:'10000000-0000-4000-8000-000000000008'};
for(const [role,id] of Object.entries(ids)){await db.query('insert into auth.users values($1,$2)',[id,role+'@example.test']);if(role!=='outsider')await db.query('insert into public.ht_members(user_id,display_name,role) values($1,$2,$3)',[id,role,role==='other'?'student':role==='instructor2'?'staff':role]);}
async function actor(role){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[ids[role]||'']);await db.exec(`set role ${role==='anon'?'anon':'authenticated'}`);}
const command=async(name,p={})=>(await db.query('select public.ht_campus_command($1,$2::jsonb) as data',[name,JSON.stringify(p)])).rows[0].data;
const state=async()=>(await db.query('select public.ht_campus_state() as data')).rows[0].data;
const scalar=async(query,args=[])=>(await db.query(query,args)).rows[0].v;
async function owner(query,args=[]){await db.exec('reset role');return db.query(query,args);}
const now=Date.now(),time=hours=>new Date(now+hours*3600000).toISOString();
await actor('staff');const cohort=(await command('saveCohort',{title:'Native coursework section',status:'active'})).id;
await command('setCohortMember',{cohort_id:cohort,user_id:ids.student,active:true});await command('setCohortMember',{cohort_id:cohort,user_id:ids.other,active:true});
const base={cohort_id:cohort,title:'Evaluate an AI-generated claim',instructions:'Document your evidence and reflection.',points_possible:100,opens_at:time(-2),due_at:time(1),closes_at:time(2),max_attempts:3,status:'published'};
const aid=(await command('saveAssignment',base)).id;
const draft=(await command('saveAssignment',{...base,title:'Private instructor draft',status:'draft'})).id;
const grade=(p)=>command('gradeAssignment',{assignment_id:aid,user_id:ids.student,disposition:'graded',status:'draft',expected_revision:0,...p});
await actor('instructor2');const otherCohort=(await command('saveCohort',{title:'Other instructor section',status:'active'})).id;
const foreign=(await command('saveAssignment',{...base,cohort_id:otherCohort,title:'Other section assignment'})).id;
await reject(()=>command('saveAssignment',{...base,id:aid,title:'Unauthorized edit'}),/Only this section/,'unrelated instructor cannot edit another assignment');
await reject(()=>grade({score:0,feedback:'Unauthorized'}),/Only this section/,'unrelated instructor cannot grade another section');
eq((await state()).assignments.map(a=>a.id),[foreign],'instructor state excludes foreign academic records');
await actor('student');eq((await state()).assignments.map(a=>a.id),[aid],'student sees published assigned section coursework only');
eq(await scalar('select count(*)::int as v from public.ht_assignments'),1,'direct RLS matches published section snapshot');
await reject(()=>command('saveAssignment',base),/Only this section/,'student cannot author coursework');
await reject(()=>command('submitAssignment',{assignment_id:draft,body:'Try draft'}),/published assignment/,'draft assignment cannot accept submissions');
await reject(()=>command('submitAssignment',{assignment_id:foreign,body:'Try foreign'}),/enrollment/,'foreign-section assignment denies submission');
await reject(()=>command('submitAssignment',{assignment_id:aid,body:' '}),/check constraint/,'submission needs body or link');
for(const link of ['javascript:alert(1)','http://example.test/file','https://user:password@example.test/file','https://example.test/\nfile','https://','https://example.test\\@evil.test','https://:443/file','https://example.test:99999/file','https://[::::]/file','https://[invalid]/file','https://[127.0.0.1]/file'])await reject(()=>command('submitAssignment',{assignment_id:aid,body:'With unsafe link',link_url:link}),/HTTPS/,'unsafe or malformed submission link rejected');
await reject(()=>command('submitAssignment',{assignment_id:aid,body:'x'.repeat(12001)}),/check constraint/,'submission body is bounded');
const attempt1=(await command('submitAssignment',{assignment_id:aid,body:'My first evidence review',user_id:ids.other,attempt_no:10,submitted_at:'2000-01-01'})).id;
let snapshot=await state(),attempt=snapshot.assignment_attempts.find(x=>x.id===attempt1);
eq(attempt.user_id,ids.student,'submission user identity ignores client impersonation');eq(attempt.attempt_no,1,'attempt number is allocated server-side');eq(new Date(attempt.submitted_at).getTime()>now-10000,true,'submission timestamp is server assigned');
for(const table of ['ht_assignments','ht_assignment_extensions','ht_assignment_attempts','ht_assignment_grades'])await reject(()=>db.query(`delete from public.${table}`),/permission denied/,'direct writes denied on '+table);
await actor('staff');await reject(()=>command('saveAssignment',{...base,id:aid,points_possible:200}),/locked/,'points lock after submission');await reject(()=>command('saveAssignment',{...base,id:aid,status:'draft'}),/locked/,'publication locks after submission');
await reject(()=>command('saveAssignment',{...base,id:aid,cohort_id:otherCohort}),/cannot move/,'section identity is immutable');
await reject(()=>grade({attempt_id:attempt1,score:101}),/points possible/,'grade cannot exceed points possible');
await reject(()=>grade({attempt_id:attempt1,score:null}),/Enter a score/,'blank score does not silently become zero');
await reject(()=>grade({attempt_id:attempt1,score:50,expected_revision:undefined}),/grade changed/,'grade requires explicit revision expectation');
await reject(()=>command('gradeAssignment',{assignment_id:draft,user_id:ids.student,score:0,feedback:'Zero',status:'draft',disposition:'graded',expected_revision:0}),/Publish/,'draft assignments cannot acquire grades and lock publication');
const notificationsBefore=await scalar('select count(*)::int as v from public.ht_notifications');
const g1=(await grade({attempt_id:attempt1,score:85,feedback:'Private draft feedback'})).id;
eq(await scalar('select count(*)::int as v from public.ht_notifications'),notificationsBefore,'draft grades do not notify learners');
eq((await state()).assignment_grades.find(g=>g.id===g1).revision,1,'first draft revision allocated');
await actor('student');eq((await state()).assignment_grades,[],'draft grade score and feedback absent from student snapshot');eq(await scalar('select count(*)::int as v from public.ht_assignment_grades'),0,'direct grade table RLS hides draft revisions');
await actor('staff');await reject(()=>grade({attempt_id:attempt1,score:88,expected_revision:0}),/grade changed/,'stale grade save rejected');
const g2=(await grade({attempt_id:attempt1,score:88,feedback:'Published assessment',status:'published',expected_revision:1})).id;
await actor('student');snapshot=await state();eq(snapshot.assignment_grades.map(g=>g.id),[g2],'learner sees only published grade revisions');eq(snapshot.assignment_grades[0].score,88,'published numeric grade visible');eq(snapshot.notifications.at(-1).href,`/ht/hub/courses/?cohort=${cohort}&tab=grades`,'published feedback links to section grade tab');
await actor('staff');await grade({attempt_id:attempt1,score:91,feedback:'Later draft',expected_revision:2});
await actor('student');eq((await state()).assignment_grades[0].id,g2,'later private draft preserves prior published grade visibility');
const attempt2=(await command('submitAssignment',{assignment_id:aid,body:'Revised review'})).id;
snapshot=await state();eq(snapshot.assignment_attempts.length,2,'resubmission preserves prior attempt');eq(snapshot.assignment_grades[0].attempt_id,attempt1,'resubmission preserves old published grade history for pending calculation');eq(snapshot.assignment_attempts.at(-1).id,attempt2,'latest attempt remains separately identified');
await actor('staff');await reject(()=>grade({attempt_id:attempt1,score:92,expected_revision:3}),/latest submission/,'grade cannot reference stale attempt after resubmission');
await grade({attempt_id:attempt2,score:94,status:'published',expected_revision:3});eq((await state()).assignment_grades.length,4,'grade revisions append without replacing prior feedback');
await actor('other');eq((await state()).assignment_attempts,[],'another enrolled learner cannot see student attempts');eq((await state()).assignment_grades,[],'another enrolled learner cannot see published individual grades');
await actor('staff');await reject(()=>command('saveAssignment',{...base,id:aid,max_attempts:1}),/attempt limit/,'attempt limit cannot truncate existing history');
await command('saveAssignment',{...base,id:aid,max_attempts:2});await actor('student');await reject(()=>command('submitAssignment',{assignment_id:aid,body:'Third attempt'}),/attempt limit/,'attempt cap enforced server-side');
await actor('staff');const zeroAid=(await command('saveAssignment',{...base,title:'Explicit zero or excusal'})).id;
await reject(()=>command('gradeAssignment',{assignment_id:zeroAid,user_id:ids.student,score:20,feedback:'No submission',disposition:'graded',status:'published',expected_revision:0}),/Without a submission/,'unsubmitted work cannot get nonzero grade');
await reject(()=>command('gradeAssignment',{assignment_id:zeroAid,user_id:ids.student,score:0,feedback:' ',disposition:'graded',status:'published',expected_revision:0}),/explanatory feedback/,'unsubmitted explicit zero requires explanation');
await command('gradeAssignment',{assignment_id:zeroAid,user_id:ids.student,score:0,feedback:'No work submitted after the agreed deadline.',disposition:'graded',status:'published',expected_revision:0});
await command('gradeAssignment',{assignment_id:zeroAid,user_id:ids.other,score:null,feedback:'Approved excusal',disposition:'excused',status:'published',expected_revision:0});
await actor('student');eq((await state()).assignment_grades.find(g=>g.assignment_id===zeroAid).score,0,'only explicit published zero is represented as zero');
await actor('other');eq((await state()).assignment_grades.find(g=>g.assignment_id===zeroAid).score,null,'excusal is null rather than a fabricated zero');
const afterExcusal=(await command('submitAssignment',{assignment_id:zeroAid,body:'Submitted after excusal'})).id;eq((await state()).assignment_grades.find(g=>g.assignment_id===zeroAid).attempt_id,null,'new submission preserves previous excusal as stale history');
await actor('staff');await reject(()=>command('gradeAssignment',{assignment_id:zeroAid,user_id:ids.other,attempt_id:afterExcusal,score:0,disposition:'excused',status:'published',expected_revision:1}),/must not include/,'excusal cannot carry score');
const closed=(await command('saveAssignment',{...base,title:'Closed assignment',due_at:time(-1),closes_at:time(-0.5)})).id;
const notOpen=(await command('saveAssignment',{...base,title:'Future open',opens_at:time(0.5)})).id;
const late=(await command('saveAssignment',{...base,title:'Late but still open',due_at:time(-1)})).id;
await actor('student');await reject(()=>command('submitAssignment',{assignment_id:closed,body:'Late'}),/closed/,'close deadline prevents submission');await reject(()=>command('submitAssignment',{assignment_id:notOpen,body:'Early'}),/not open/,'opening time enforced');
await command('submitAssignment',{assignment_id:late,body:'Late work is still accepted before close'});eq((await state()).assignment_attempts.some(x=>x.assignment_id===late),true,'passing due date alone does not reject work');
await actor('staff');const extension={assignment_id:closed,user_id:ids.student,due_at:time(1),closes_at:time(2)};
await reject(()=>command('setAssignmentExtension',{...extension,due_at:time(-2)}),/cannot shorten/,'extension cannot shorten original due date');await reject(()=>command('setAssignmentExtension',{...extension,due_at:time(3)}),/open\/due\/close/,'extension effective date order enforced');
await command('setAssignmentExtension',extension);await actor('student');await command('submitAssignment',{assignment_id:closed,body:'Within my extension'});eq((await state()).assignment_extensions.length,1,'learner sees own deadline extension');
await actor('other');eq((await state()).assignment_extensions.length,0,'other learner cannot see extension');await reject(()=>command('submitAssignment',{assignment_id:closed,body:'Another student'}),/closed/,'extension does not extend entire class deadline');
await actor('staff');await reject(()=>command('setAssignmentExtension',{...extension,assignment_id:draft}),/Publish/,'draft assignment cannot receive extension');
await reject(()=>command('saveAssignment',{...base,id:closed,title:'Closed assignment',due_at:time(1.5),closes_at:time(2.5)}),/existing extension/,'base deadline edits cannot invalidate individual extension');
await command('setAssignmentExtension',{...extension,clear:true});eq((await state()).assignment_extensions.length,0,'clearing extension restores base deadline explicitly');
const unbounded=(await command('saveAssignment',{...base,title:'No deadline',opens_at:null,due_at:null,closes_at:null})).id;
await reject(()=>command('setAssignmentExtension',{...extension,assignment_id:unbounded}),/add a deadline/,'extension cannot impose finite deadline on unbounded assignment');
for(const field of ['opens_at','due_at','closes_at'])for(const value of ['infinity','-infinity'])await reject(()=>command('saveAssignment',{...base,title:'Nonfinite date',[field]:value}),/date/,'assignment rejects nonfinite '+field);
for(const field of ['due_at','closes_at'])await reject(()=>command('setAssignmentExtension',{...extension,[field]:'infinity'}),/extension/,'extension rejects nonfinite '+field);
await reject(()=>command('saveAssignment',{...base,title:'Invalid dates',opens_at:time(3)}),/date/,'assignment date order validated');
for(const points of [0,-1,10001])await reject(()=>command('saveAssignment',{...base,points_possible:points}),/check constraint/,'points possible bounded');
for(const max_attempts of [0,11])await reject(()=>command('saveAssignment',{...base,max_attempts}),/check constraint/,'attempt count bounded');
await command('setCohortMember',{cohort_id:cohort,user_id:ids.instructor2,active:true});await actor('instructor2');eq((await state()).assignments.some(x=>x.id===aid),true,'unassigned staff on roster receives learner access');eq((await state()).assignments.some(x=>x.id===draft),false,'staff learner cannot see section drafts');await reject(()=>grade({attempt_id:attempt2,score:99,expected_revision:4}),/Only this section/,'enrolled staff learner cannot manage grades');
await command('submitAssignment',{assignment_id:unbounded,body:'Staff learner work'});
await actor('staff');await command('setCohortMember',{cohort_id:cohort,user_id:ids.staff,active:true});await reject(()=>command('submitAssignment',{assignment_id:unbounded,body:'My own assignment'}),/instructor cannot submit/,'assigned instructor cannot self-submit');await reject(()=>command('gradeAssignment',{assignment_id:unbounded,user_id:ids.staff,score:0,feedback:'Own grade',disposition:'graded',status:'published',expected_revision:0}),/own coursework/,'instructor cannot self-grade');
await actor('leadership');eq((await state()).assignments,[],'leadership role does not expose academic records');await reject(()=>command('submitAssignment',{assignment_id:unbounded,body:'Leadership'}),/enrollment/,'leadership does not gain learner access');
await actor('admin');eq((await state()).assignments.some(x=>x.id===foreign),true,'campus administrator can inspect section coursework');
await actor('staff');await command('setCohortMember',{cohort_id:cohort,user_id:ids.student,active:false});await actor('student');eq((await state()).assignments,[],'removed learner loses section records');eq(await scalar('select count(*)::int as v from public.ht_assignment_attempts'),0,'removed learner loses direct attempt history read');await reject(()=>command('submitAssignment',{assignment_id:unbounded,body:'Removed'}),/enrollment/,'removed learner cannot resubmit');
await actor('staff');await reject(()=>grade({attempt_id:attempt2,score:99,expected_revision:4}),/active enrolled/,'removed learner cannot be newly graded');await command('setCohortMember',{cohort_id:cohort,user_id:ids.student,active:true});
// Concurrent request promises on the embedded connection verify serialization outcomes;
// staging multi-connection tests are still needed to exercise actual PostgreSQL lock waits.
const once=(await command('saveAssignment',{...base,title:'One permitted attempt',max_attempts:1})).id;
await actor('student');const attemptsAtOnce=await Promise.allSettled([command('submitAssignment',{assignment_id:once,body:'First request'}),command('submitAssignment',{assignment_id:once,body:'Competing request'})]);
eq(attemptsAtOnce.filter(x=>x.status==='fulfilled').length,1,'competing requests cannot both consume last attempt slot');eq((await state()).assignment_attempts.filter(x=>x.assignment_id===once).map(x=>x.attempt_no),[1],'competing submissions leave one unique server attempt');
const concurrentAttempt=attemptsAtOnce.find(x=>x.status==='fulfilled').value.id;
await actor('staff');const review={assignment_id:once,user_id:ids.student,attempt_id:concurrentAttempt,score:50,feedback:'One review',disposition:'graded',status:'published',expected_revision:0};const gradesAtOnce=await Promise.allSettled([command('gradeAssignment',review),command('gradeAssignment',{...review,score:75})]);
eq(gradesAtOnce.filter(x=>x.status==='fulfilled').length,1,'competing grade requests cannot silently overwrite expected revision');eq((await state()).assignment_grades.filter(x=>x.assignment_id===once).map(x=>x.revision),[1],'competing grades preserve one revision');
// Existing command wrappers and pathway completion remain independent.
await command('sendMessage',{recipient_id:ids.student,body:'Coursework wrapper regression'});const session=(await command('saveClassSession',{cohort_id:cohort,audience:'cohort',title:'Course live session',starts_at:time(1),ends_at:time(2)})).id;
eq((await state()).class_sessions.some(x=>x.id===session),true,'coursework wrapper preserves classroom scheduling');await actor('student');eq((await state()).messages.some(x=>x.body==='Coursework wrapper regression'),true,'coursework wrapper preserves private messaging');eq((await state()).enrollments.length,0,'published coursework grades do not issue pathway completion');
await actor('staff');const pathway=(await command('saveCourse',{title:'Independent learning regression',status:'draft'})).id;const activity=(await command('saveModule',{course_id:pathway,title:'A reading activity',body:'Read and reflect.',position:1})).id;await command('saveCourse',{id:pathway,title:'Independent learning regression',status:'published'});await actor('student');await command('enroll',{course_id:pathway});await command('completeModule',{module_id:activity});eq(Boolean((await state()).enrollments.find(x=>x.course_id===pathway).credential_id),true,'existing learning completion still issues its independent credential');eq((await state()).assignment_grades.some(x=>x.assignment_id===aid),true,'learning completion preserves coursework grade history');
await actor('staff');await command('saveCohort',{id:cohort,title:'Archived section',status:'archived'});eq((await state()).assignments.some(x=>x.id===aid),true,'instructor retains archived academic history read');await reject(()=>command('saveAssignment',{...base,id:aid}),/Archived/,'archived section cannot edit assignments');await reject(()=>grade({attempt_id:attempt2,score:99,expected_revision:4}),/Archived/,'archived section cannot grade');await reject(()=>command('setAssignmentExtension',extension),/Archived/,'archived section cannot change extensions');await actor('student');eq((await state()).assignments,[],'learner cannot access archived section coursework');await reject(()=>command('submitAssignment',{assignment_id:unbounded,body:'Archived'}),/Archived/,'archived section cannot accept submission');
await actor('staff');await command('saveCohort',{id:cohort,title:'Active again',status:'active'});
await actor('admin');await command('setMember',{user_id:ids.student,display_name:'student',role:'student',active:false});await actor('student');await reject(()=>command('submitAssignment',{assignment_id:unbounded,body:'Inactive'}),/membership/,'inactive campus membership blocks submissions');eq(await scalar('select count(*)::int as v from public.ht_assignments'),0,'inactive membership blocks direct coursework read');
await actor('outsider');await reject(()=>command('submitAssignment',{assignment_id:aid,body:'Outsider'}),/membership/,'nonmember cannot submit');await actor('anon');await reject(()=>state(),/permission denied/,'anonymous cannot load coursework snapshot');await reject(()=>db.query('select * from public.ht_assignment_grades'),/permission denied/,'anonymous cannot read academic tables');
await owner('select 1');const security=(await db.query("select prosecdef,proconfig,has_function_privilege('anon',oid,'EXECUTE') as anon from pg_proc where oid='ht_private.academic_command(text,jsonb)'::regprocedure")).rows[0];eq(security,{prosecdef:true,proconfig:['search_path=""'],anon:false},'checked writer is private, fixed search path, and denied to anon');
eq((await db.query("select bool_and(relrowsecurity) as enabled from pg_class where relname in ('ht_assignments','ht_assignment_extensions','ht_assignment_attempts','ht_assignment_grades')")).rows[0].enabled,true,'all academic tables enforce RLS');
eq(await scalar("select count(*)::int as v from ht_private.audit_log where action='submitAssignment'"),7,'only successful submissions produce audit metadata');
console.log(`Passed ${checks} academic database checks. No remote database was modified.`);await db.close();
