import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const source=await readFile(new URL('../../ht/hub/campus-store.js',import.meta.url),'utf8');
const {createCampusStore}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const values=new Map(),storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},key='ht-campus-demo-v2';
let time=Date.parse('2026-09-21T15:00:00Z'),checks=0;const options={storage,now:()=>time};
const student=createCampusStore({...options,demoRole:'student'}),staff=createCampusStore({...options,demoRole:'staff'}),leadership=createCampusStore({...options,demoRole:'leadership'});
const eq=(a,b,msg)=>{assert.deepEqual(a,b,msg);console.log(`ok ${++checks} - ${msg}`);};
const reject=async(fn,re,msg)=>{await assert.rejects(fn,re,msg);console.log(`ok ${++checks} - ${msg}`);};
const raw=()=>JSON.parse(storage.getItem(key));const modify=fn=>{const s=raw();fn(s);storage.setItem(key,JSON.stringify(s));};
const iso=ms=>new Date(ms).toISOString();
let s=await student.load(),teacher=await staff.load();
const uid=s.user.id,teacherId=teacher.user.id,cohort=s.cohorts[0],foreign='d0000000-0000-4000-8000-000000000003',academicKeys=['assignments','assignment_extensions','assignment_attempts','assignment_grades'];
const first=s.assignments[0],draft=teacher.assignments.find(a=>a.status==='draft');
eq(s.assignments.map(a=>a.id),['d0000000-0000-4000-8000-000000000001'],'student sees published assignment in own section only');
eq(teacher.assignments.length,2,'instructor sees own published assignment and draft');
eq((await leadership.load()).assignments,[],'leadership cannot access individual coursework');
eq(s.assignment_attempts.length+s.assignment_grades.length,0,'demo does not invent submission or grading history');
eq([Date.parse(first.due_at)>time,new Date(first.due_at).getHours(),new Date(first.due_at).getMinutes()],[true,23,59],'sample assignment is due in the future at 11:59 PM local');
eq(raw()._academics_version,1,'new demo persists academic upgrade marker on initial load');
await student.command('post',{channel:'Campus',body:'Preserve my existing campus conversation'});
await student.command('readMessages',{message_ids:[s.messages[0].id]});
await student.command('demoJoinSession',{session_id:s.class_sessions[0].id});
let prior=raw();for(const k of academicKeys)delete prior[k];delete prior._academics_version;storage.setItem(key,JSON.stringify(prior));
const preserved=JSON.stringify(prior);await student.load();const after=raw();for(const k of academicKeys)delete after[k];delete after._academics_version;
eq(JSON.stringify(after),preserved,'academic migration preserves every earlier demo-v2 field and record');
eq(raw().assignments.length,3,'existing demo receives only the three additive fictional assignments');
const seedDate=raw().assignments[0].due_at;time+=60000;await student.load();
eq(raw().assignments.length,3,'repeated loads do not duplicate academic seeds');eq(raw().assignments[0].due_at,seedDate,'repeated loads do not change original academic deadlines');
await reject(()=>student.command('saveAssignment',{...first,title:'Self-authored'}),/Staff access/,'student cannot author an assignment');
await reject(()=>staff.command('saveAssignment',{...raw().assignments.find(a=>a.id===foreign),title:'Foreign edit'}),/section you manage/,'unrelated instructor cannot edit foreign assignment');
await reject(()=>student.command('submitAssignment',{assignment_id:foreign,body:'Unauthorized'}),/section enrollment/,'foreign-cohort direct submission is denied');
await reject(()=>student.command('submitAssignment',{assignment_id:draft.id,body:'Hidden draft'}),/section enrollment/,'student cannot submit an unpublished assignment by ID');
await staff.command('saveAssignment',{...draft,status:'published'});
eq((await student.load()).assignments.some(a=>a.id===draft.id),true,'instructor publishing makes assignment available to enrolled learner');
for(const update of [{points_possible:0},{points_possible:10001},{points_possible:''},{max_attempts:0},{max_attempts:11},{max_attempts:1.5},{title:'x'.repeat(161)},{instructions:'x'.repeat(12001)},{due_at:'invalid'},{opens_at:'2027-01-01T00:00:00Z'}])await reject(()=>staff.command('saveAssignment',{...first,...update}),/Points|points|attempt|160|12000|valid due|dates must/,'invalid assignment configuration rejected');
for(const payload of [{body:''},{body:'x'.repeat(12001)},{link_url:'javascript:alert(1)'},{link_url:'http://example.test'},{link_url:'https://user:password@example.test/project'},{link_url:'https://example.test/a b'},{link_url:'https://example.test/\\evil'},{link_url:'https://'},{link_url:'https://example.test/'+ 'x'.repeat(2000)}])await reject(()=>student.command('submitAssignment',{assignment_id:first.id,...payload}),/work or|12000|HTTPS/,'empty, oversized, executable or credentialed submission is rejected');
const attempt1=(await student.command('submitAssignment',{assignment_id:first.id,body:'My project brief',user_id:teacherId,attempt_no:99,submitted_at:'2000-01-01T00:00:00Z'})).id;
s=await student.load();const storedAttempt=s.assignment_attempts.find(a=>a.id===attempt1);
eq([storedAttempt.user_id,storedAttempt.attempt_no,storedAttempt.submitted_at],[uid,1,iso(time)],'submission actor, attempt number and time come from the store');
await reject(()=>staff.command('saveAssignment',{...first,points_possible:200}),/locked/,'points lock after a submission');
await reject(()=>staff.command('saveAssignment',{...first,status:'draft'}),/locked/,'publication locks after a submission');
const grade={assignment_id:first.id,user_id:uid,attempt_id:attempt1,score:85,feedback:'Private draft feedback',disposition:'graded',status:'draft',expected_revision:0};
const noticeCount=(await student.load()).notifications.length;
await staff.command('gradeAssignment',grade);
eq((await student.load()).assignment_grades,[],'draft grade and feedback are absent from student state');
eq((await student.load()).notifications.length,noticeCount,'draft grade does not notify student');
eq((await staff.load()).assignment_grades[0].revision,1,'instructor draft starts append-only grade revision history');
await reject(()=>staff.command('gradeAssignment',grade),/grade changed/,'stale expected revision prevents draft overwrite');
await staff.command('gradeAssignment',{...grade,status:'published',feedback:'Published feedback',expected_revision:1});
s=await student.load();eq(s.assignment_grades.map(g=>[g.revision,g.feedback]),[[2,'Published feedback']],'student receives only published revision');
eq(s.notifications.at(-1).href,`/ht/hub/courses/?cohort=${cohort.id}&tab=grades`,'published grade notification opens course Grades tab');
await staff.command('gradeAssignment',{...grade,score:90,expected_revision:2});
eq((await student.load()).assignment_grades.map(g=>g.revision),[2],'later private draft does not hide prior published grade');
eq((await staff.load()).assignment_grades.map(g=>g.revision),[1,2,3],'instructor retains complete grade revision history');
const attempt2=(await student.command('submitAssignment',{assignment_id:first.id,link_url:'https://example.test/portfolio/project'})).id;
s=await student.load();eq(s.assignment_attempts.map(a=>a.attempt_no),[1,2],'resubmission appends attempt history');
eq(s.assignment_grades[0].attempt_id,attempt1,'resubmission preserves earlier published grade without pretending it grades latest work');
await reject(()=>staff.command('gradeAssignment',{...grade,expected_revision:3}),/latest submission/,'older attempt cannot be graded after resubmission');
await reject(()=>staff.command('gradeAssignment',{...grade,attempt_id:attempt2,expected_revision:2}),/grade changed/,'expected revision includes private draft revisions');
for(const score of [null,'',-1,101])await reject(()=>staff.command('gradeAssignment',{...grade,attempt_id:attempt2,score,expected_revision:3}),/valid score|between zero/,'invalid score rejected without adding grade history');
await staff.command('gradeAssignment',{...grade,attempt_id:attempt2,score:92,status:'published',expected_revision:3});
eq((await student.load()).assignment_grades.at(-1).attempt_id,attempt2,'fresh published grade explicitly grades latest submission');
await student.command('submitAssignment',{assignment_id:first.id,body:'Final revision'});
await reject(()=>student.command('submitAssignment',{assignment_id:first.id,body:'One attempt too many'}),/every allowed/,'maximum submission attempts enforced');
await reject(()=>staff.command('saveAssignment',{...first,max_attempts:2}),/below an existing/,'attempt limit cannot shrink below submission history');
const make=async(title,extra={})=>{const id=(await staff.command('saveAssignment',{cohort_id:cohort.id,title,instructions:'Explain your work.',points_possible:20,max_attempts:10,status:'published',...extra})).id;return (await staff.load()).assignments.find(a=>a.id===id);};
const emptyAssignment=await make('Unsubmitted grade distinctions');
const noAttempt={assignment_id:emptyAssignment.id,user_id:uid,attempt_id:null,disposition:'graded',status:'published',expected_revision:0};
await reject(()=>staff.command('gradeAssignment',{...noAttempt,score:10,feedback:'No work'}),/explicit zero/,'positive score without submission rejected');
await reject(()=>staff.command('gradeAssignment',{...noAttempt,score:0,feedback:''}),/explicit zero/,'zero without submission requires explanatory feedback');
await staff.command('gradeAssignment',{...noAttempt,score:0,feedback:'No submission was received by the agreed deadline.'});
eq((await student.load()).assignment_grades.find(g=>g.assignment_id===emptyAssignment.id).score,0,'explicit published zero is distinct from ungraded work');
await reject(()=>staff.command('gradeAssignment',{...noAttempt,disposition:'excused',score:0,expected_revision:1}),/numeric score/,'excused grade cannot also carry a numeric score');
await staff.command('gradeAssignment',{...noAttempt,disposition:'excused',score:null,feedback:'Excused by instructor',expected_revision:1});
eq((await student.load()).assignment_grades.filter(g=>g.assignment_id===emptyAssignment.id).map(g=>[g.disposition,g.score]),[['graded',0],['excused',null]],'excused revision preserves earlier zero and has no numeric score');
eq((await student.load()).assignment_grades.some(g=>g.assignment_id===draft.id),false,'never graded assignment has no fabricated zero');
eq((await student.load()).enrollments[0].credential_id,null,'coursework grading does not issue a pathway completion credential');
const base=time,timed=await make('Deadline and extension practice',{opens_at:iso(base+60000),due_at:iso(base+120000),closes_at:iso(base+180000)});
await reject(()=>student.command('submitAssignment',{assignment_id:timed.id,body:'Early'}),/not opened/,'submission before open is rejected');
time=base+60000;await student.command('submitAssignment',{assignment_id:timed.id,body:'At opening'});
time=base+120001;await student.command('submitAssignment',{assignment_id:timed.id,body:'After due, before close'});
eq((await student.load()).assignment_attempts.filter(a=>a.assignment_id===timed.id).at(-1).submitted_at>timed.due_at,true,'late submission remains allowed before close and keeps actual timestamp');
time=base+180000;await student.command('submitAssignment',{assignment_id:timed.id,body:'At close boundary'});
time++;await reject(()=>student.command('submitAssignment',{assignment_id:timed.id,body:'Too late'}),/closed/,'close date blocks subsequent submission');
for(const extension of [{due_at:iso(base+119999)},{closes_at:iso(base+179999)},{due_at:iso(base+300000),closes_at:iso(base+200000)}])await reject(()=>staff.command('setAssignmentExtension',{assignment_id:timed.id,user_id:uid,...extension}),/lengthen|dates must/,'shortening or misordered extension rejected');
await staff.command('setAssignmentExtension',{assignment_id:timed.id,user_id:uid,due_at:iso(base+300000),closes_at:iso(base+360000)});
eq((await student.load()).assignment_extensions[0].due_at,iso(base+300000),'student sees their effective deadline extension');
await student.command('submitAssignment',{assignment_id:timed.id,body:'Allowed by instructor extension'});
eq((await student.load()).assignment_attempts.filter(a=>a.assignment_id===timed.id).length,4,'extension permits submission after original close');
await reject(()=>staff.command('saveAssignment',{...timed,due_at:iso(base+310000),closes_at:iso(base+400000)}),/lengthen/,'base deadline change cannot invalidate an existing extension');
await staff.command('setAssignmentExtension',{assignment_id:timed.id,user_id:uid,clear:true});
eq((await student.load()).assignment_extensions,[],'explicit clear removes extension');
await reject(()=>student.command('submitAssignment',{assignment_id:timed.id,body:'Closed again'}),/closed/,'clearing extension restores original close restriction');
await reject(()=>staff.command('setAssignmentExtension',{assignment_id:emptyAssignment.id,user_id:uid,due_at:iso(time+60000)}),/introduce/,'finite deadline cannot be introduced as extension of an unbounded date');
const unpublished=await make('Hidden extension target',{status:'draft'});
await reject(()=>staff.command('setAssignmentExtension',{assignment_id:unpublished.id,user_id:uid}),/Publish the assignment/,'unpublished assignment cannot receive extensions');
await reject(()=>staff.command('gradeAssignment',{...noAttempt,assignment_id:unpublished.id,score:0,feedback:'No submission'}),/Publish the assignment/,'unpublished assignment cannot be graded and trapped behind a publication lock');
await staff.command('setCohortMember',{cohort_id:cohort.id,user_id:uid,active:false});
s=await student.load();eq(academicKeys.map(k=>s[k].length),[0,0,0,0],'removed enrollment hides all section academic records');
await reject(()=>student.command('submitAssignment',{assignment_id:first.id,body:'Removed'}),/section enrollment/,'removed member cannot submit via old assignment link');
await reject(()=>staff.command('gradeAssignment',{...grade,expected_revision:4}),/active enrolled/,'removed learner cannot be graded');
await reject(()=>staff.command('setAssignmentExtension',{assignment_id:timed.id,user_id:uid,clear:true}),/active enrolled/,'removed learner cannot receive extension changes');
await staff.command('setCohortMember',{cohort_id:cohort.id,user_id:uid,active:true});
await staff.command('setCohortMember',{cohort_id:cohort.id,user_id:teacherId,active:true});
await reject(()=>staff.command('submitAssignment',{assignment_id:first.id,body:'Instructor self-submit'}),/section enrollment/,'instructor cannot submit own assignment even on roster');
await reject(()=>staff.command('gradeAssignment',{...noAttempt,user_id:teacherId,score:0,feedback:'Self grade'}),/another active enrolled/,'instructor cannot self-grade');
const otherCohort=raw().cohorts.find(c=>c.id!==cohort.id);
modify(data=>data.cohort_members.push({cohort_id:otherCohort.id,user_id:teacherId,active:true,joined_at:iso(time)}));
eq((await staff.load()).assignments.some(a=>a.id===foreign),true,'staff enrolled as learner sees published assignment in another section');
const staffAttempt=(await staff.command('submitAssignment',{assignment_id:foreign,body:'Staff participating as a learner'})).id;
eq((await staff.load()).assignment_attempts.some(a=>a.id===staffAttempt),true,'unassigned staff can submit as an enrolled learner');
await reject(()=>staff.command('gradeAssignment',{assignment_id:foreign,user_id:teacherId,attempt_id:staffAttempt,score:20,feedback:'No',disposition:'graded',status:'published',expected_revision:0}),/section you manage/,'enrolled staff learner cannot grade foreign section');
modify(data=>data.members.find(m=>m.user_id===uid).active=false);
eq((await student.load()).assignments,[],'inactive institutional membership hides academic records despite roster');
await reject(()=>student.command('submitAssignment',{assignment_id:draft.id,body:'Inactive'}),/active HT membership/,'inactive membership denies academic writes');
modify(data=>data.members.find(m=>m.user_id===uid).active=true);
await staff.command('saveCohort',{...cohort,status:'archived'});
eq((await student.load()).assignments,[],'archived section hides learner academic records');
eq((await staff.load()).assignments.some(a=>a.id===first.id),true,'assigned instructor retains archived academic history');
for(const [command,payload] of [['saveAssignment',first],['submitAssignment',{assignment_id:first.id,body:'Archived'}],['gradeAssignment',grade],['setAssignmentExtension',{assignment_id:timed.id,user_id:uid,clear:true}]])await reject(()=>(command==='submitAssignment'?student:staff).command(command,payload),/active section|section enrollment/,'archived section rejects '+command);
const guest=createCampusStore({client:{auth:{getSession:async()=>({data:{session:null}})},rpc:()=>{throw Error('Guest must not call RPC');}}});
const guestState=await guest.load();eq(academicKeys.map(k=>guestState[k].length),[0,0,0,0],'signed-out illustration contains no section coursework');
await reject(()=>guest.command('submitAssignment',{assignment_id:first.id,body:'Guest'}),/Sign in/,'guest cannot submit work');
let calls=[];const live=createCampusStore({client:{auth:{getSession:async()=>({data:{session:{user:{id:uid}}}})},rpc:async(name,payload)=>{calls.push([name,payload]);return name==='ht_campus_state'?{data:{member:{user_id:uid,role:'student'},assignments:[first],assignment_extensions:[],assignment_attempts:[storedAttempt],assignment_grades:[]}}:{data:{ok:true,id:'persisted-academic-id'}};}}});
eq((await live.load()).assignment_attempts[0].id,attempt1,'live store retains real academic state arrays');
for(const [name,payload] of [['saveAssignment',first],['submitAssignment',{assignment_id:first.id,body:'Real work'}],['gradeAssignment',grade],['setAssignmentExtension',{assignment_id:first.id,user_id:uid,clear:true}]]){await live.command(name,payload);eq(calls.at(-1),['ht_campus_command',{p_name:name,p_payload:payload}],'live '+name+' dispatches unchanged validated RPC contract');}
for(const store of [student,staff,leadership,guest,live])store.destroy();
console.log(`Passed ${checks} academic store checks. No remote database was modified.`);
