import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();let checks=0;
const eq=(a,b,msg)=>{assert.deepEqual(a,b,msg);console.log(`ok ${++checks} - ${msg}`);};
const reject=async(fn,re,msg)=>{await assert.rejects(fn,re,msg);console.log(`ok ${++checks} - ${msg}`);};
const sql=path=>readFile(new URL('../../'+path,import.meta.url),'utf8');
await db.exec("create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth,public to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;");
await db.exec(await sql('supabase/migrations/20260921180637_ht_campus_hub.sql'));
await db.exec(await readFile(new URL('classroom-legacy-bootstrap.sql',import.meta.url),'utf8'));
async function legacyFunction(file,name){const source=await sql('supabase/migrations/'+file),re=new RegExp('create (?:or replace )?function public\\.'+name+'\\(','i');const start=source.search(re);assert.ok(start>=0,name);const body=source.indexOf('$$',start),end=source.indexOf('$$;',body+2);await db.exec(source.slice(start,end+3));}
for(const [f,names] of [['0036_academy_room.sql',['ea_room_in_session']],['0037_ht_room.sql',['ea_room_is_host','ea_room_rotate_link','ea_room_set_hosts','ea_room_publish_replay']],['0042_class_core.sql',['ea_class_can','ea_class_is_host']],['0054_ht_room_features.sql',['ea_room_reader','ea_room_state']],['0043_class_presence.sql',['ea_class_attendance_rows']],['0047_class_help.sql',['ea_class_help_queue','ea_class_help_may_ask']],['0049_class_warmups.sql',['ea_class_names']]])for(const name of names)await legacyFunction(f,name);
await db.exec(`alter table public.ea_rooms enable row level security;alter table public.ea_room_members enable row level security;alter table public.ea_room_replays enable row level security;alter table public.ea_room_hands enable row level security;grant select on public.ea_rooms,public.ea_room_members,public.ea_room_replays,public.ea_room_hands to authenticated;grant update(title,is_live,max_participants,live_since,ended_at,updated_at,host_name,warmup_q,next_title,next_at) on public.ea_rooms to authenticated;grant insert,update,delete on public.ea_room_hands to authenticated;
create policy rooms_admin_read on public.ea_rooms for select to authenticated using(public.ea_room_is_host(id));create policy rooms_admin_update on public.ea_rooms for update to authenticated using(public.ea_room_is_host(id)) with check(public.ea_room_is_host(id));create policy room_members_admin_read on public.ea_room_members for select to authenticated using(public.ea_room_is_host(room_id));create policy room_replays_admin_read on public.ea_room_replays for select to authenticated using(public.ea_room_is_host(room_id));create policy room_hands_all on public.ea_room_hands for all to authenticated using(user_id=auth.uid() or public.ea_room_is_host(room_id)) with check(user_id=auth.uid() or public.ea_room_is_host(room_id));`);
for(const t of ['ea_class_events','ea_class_summaries','ea_class_transcripts','ea_class_presence','ea_class_board_ops','ea_class_warmups','ea_class_scores','ea_class_help','ea_class_reminders','ea_opil_materials']){
 await db.exec(`alter table public.${t} enable row level security;grant select,insert,update,delete on public.${t} to authenticated;create policy legacy_all on public.${t} for all to authenticated using(public.ea_is_admin() or public.ea_class_can(room_key)) with check(public.ea_is_admin() or public.ea_class_can(room_key));`);
}
await db.exec(await sql('supabase/migrations/20260921193229_ht_cohort_classrooms.sql'));
console.log(`ok ${++checks} - classroom migration executes over legacy helper bodies and policies`);
const ids={student:'10000000-0000-4000-8000-000000000001',staff:'10000000-0000-4000-8000-000000000002',other:'10000000-0000-4000-8000-000000000004',instructor2:'10000000-0000-4000-8000-000000000008',leadership:'10000000-0000-4000-8000-000000000003',admin:'10000000-0000-4000-8000-000000000006',legacy:'10000000-0000-4000-8000-000000000099',outsider:'10000000-0000-4000-8000-000000000098'};
for(const [role,id] of Object.entries(ids)){await db.query('insert into auth.users values($1,$2)',[id,role+'@example.test']);if(!['legacy','outsider'].includes(role))await db.query('insert into public.ht_members(user_id,display_name,role) values($1,$2,$3)',[id,role,role==='other'?'student':role==='instructor2'?'staff':role]);}
async function actor(role){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[ids[role]||'']);await db.exec(`set role ${role==='anon'?'anon':'authenticated'}`);}
async function owner(query,args=[]){await db.exec('reset role');return db.query(query,args);}
const command=async(name,p={})=>(await db.query('select public.ht_campus_command($1,$2::jsonb) as data',[name,JSON.stringify(p)])).rows[0].data;
const state=async()=>(await db.query('select public.ht_campus_state() as data')).rows[0].data;
const access=async(slug)=>(await db.query('select public.ht_classroom_access($1) as data',[slug])).rows[0].data;
const scalar=async(query,args=[])=>(await db.query(query,args)).rows[0].v;
await actor('staff');
const a=(await command('saveCohort',{title:'Cohort A',description:'First cohort',status:'active'})).id;
await command('setCohortMember',{cohort_id:a,user_id:ids.student,active:true});
await actor('instructor2');
const b=(await command('saveCohort',{title:'Cohort B',description:'Second cohort',status:'active'})).id;
await command('setCohortMember',{cohort_id:b,user_id:ids.other,active:true});
await reject(()=>command('setCohortMember',{cohort_id:a,user_id:ids.other,active:true}),/do not manage/,'instructor cannot change another cohort roster');
const schedule={title:'Concurrent session',description:'Agenda',starts_at:new Date(Date.now()-60000).toISOString(),ends_at:new Date(Date.now()+3600000).toISOString(),status:'scheduled',audience:'cohort'};
const bs=(await command('saveClassSession',{...schedule,cohort_id:b})).id;
await actor('staff');
const as=(await command('saveClassSession',{...schedule,cohort_id:a})).id;
const as2=(await command('saveClassSession',{...schedule,title:'Another session',cohort_id:a})).id;
const campus=(await command('saveClassSession',{...schedule,title:'Campus conversation',audience:'campus'})).id;
let s=await state(),session=s.class_sessions.find(x=>x.id===as),session2=s.class_sessions.find(x=>x.id===as2);
eq(session.room_slug.length,28,'managed slug fits legacy room slug constraint');
eq(new Set(s.class_sessions.map(x=>x.room_id)).size,3,'every scheduled session has a unique room');
eq((await access(session.room_slug)).is_host,true,'assigned instructor is host');
await reject(()=>db.query('update public.ea_rooms set title=$1 where id=$2',['Bypass',session.room_id]),/campus workspace/,'direct room identity edit rejected');
await reject(()=>db.query('select public.ea_room_rotate_link($1)',[session.room_id]),/roster/,'managed invite-key rotation rejected');
await actor('student');s=await state();eq(s.cohorts.map(x=>x.id),[a],'student sees own cohort only');eq(s.cohort_members.length,1,'student cannot see whole cohort roster');eq(s.class_sessions.length,3,'student sees own sessions and campus session');
eq((await access(session.room_slug)).can_join,true,'active cohort member may join own classroom');
await reject(()=>command('setCohortMember',{cohort_id:b,user_id:ids.student}),/instructor/,'student cannot self-enroll in cohort');
await reject(()=>command('demoJoinSession',{session_id:as}),/explicit demo/,'live RPC rejects simulated attendance');
eq(await scalar('select public.ea_room_reader($1) as v',['room:'+session.room_id]),false,'unpublished classroom record hidden from student before live attendance');
await actor('other');eq((await access(session.room_slug)).can_join,false,'wrong-cohort student denied');
eq(await scalar('select public.ea_class_can($1) as v',['room:'+session.room_id]),false,'classroom plugins deny wrong cohort');
await actor('legacy');eq((await access(session.room_slug)).can_join,false,'Academy administrator gains no managed classroom access');
eq(await scalar('select public.ea_room_is_host($1) as v',[session.room_id]),false,'legacy room host helper cannot bypass campus membership');
eq(await scalar('select public.ea_class_is_host($1) as v',['room:'+session.room_id]),false,'legacy class host helper cannot bypass campus membership');
await reject(()=>db.query('select public.ea_room_set_hosts($1,$2)',[session.room_id,['legacy@example.test']]),/campus workspace/,'Academy admin cannot grant managed hosts by email');
const unknown='htc-000000000000000000000000';eq(await access(unknown),{managed:true,can_join:false,is_host:false,room_id:null},'unknown managed slug fails closed');
await owner("insert into public.ea_rooms(slug,title,open_door,host_emails) values($1,'Orphan managed',true,array['legacy@example.test'])",[unknown]);await actor('legacy');eq((await access(unknown)).can_join,false,'orphan managed room cannot use open door or host email');
eq((await scalar('select public.ea_room_state($1,$2) as v',['any-key',session.room_slug])).can_join,false,'managed state ignores invitation-key authorization');
await actor('leadership');s=await state();eq(s.cohorts.length,0,'leadership has no cohort access by role alone');eq(s.class_sessions.map(x=>x.id),[campus],'leadership sees campus session only');
await owner('update public.ea_rooms set is_live=true,live_since=now()-interval \'1 minute\' where id in ($1,$2)',[session.room_id,session2.room_id]);
await owner('insert into public.ea_room_members(room_id,user_id) values($1,$2)',[session.room_id,ids.student]);
await owner('insert into public.ea_class_events(room_key,user_id,body) values($1,$2,$3)',['room:'+session.room_id,ids.student,'Protected session event']);
await owner('insert into public.ea_opil_materials(room_key,uploaded_by,file_path,body) values($1,$2,$3,$4)',['room:'+session.room_id,ids.staff,`materials/${ids.staff}/room/${session.room_id}/file.pdf`,'Protected material']);
await owner('insert into storage.objects(bucket_id,name,owner_id) values($1,$2,$3)',['opil-files',`materials/${ids.staff}/room/${session.room_id}/file.pdf`,ids.staff]);
await owner('insert into public.ea_class_presence(room_key,user_id,state,first_seen,last_seen,seconds,waited_s) values($1,$2,\'in\',now(),now(),120,0)',['room:'+session.room_id,ids.student]);
await owner('insert into public.ea_class_help(room_key,user_id,text,created_at) values($1,$2,\'Private classroom help\',now())',['room:'+session.room_id,ids.student]);
await actor('student');s=await state();eq(s.session_attendance.length,1,'actual room join yields one session attendance record');eq(s.session_attendance[0].session_id,as,'attendance belongs to exact session');
eq(await scalar('select public.ea_room_in_session($1) as v',[session.room_id]),true,'authorized real attendee is in own live session');eq(await scalar('select public.ea_room_reader($1) as v',['room:'+session.room_id]),true,'current attendee can read live classroom records');
await actor('legacy');eq(await scalar('select count(*)::int as v from public.ea_opil_materials'),0,'OPIL program-team material policy cannot read managed files');eq(await scalar('select count(*)::int as v from storage.objects'),0,'OPIL-wide storage policy cannot expose managed file bytes');eq(await scalar('select count(*)::int as v from public.ea_class_help'),0,'program team cannot read managed help');eq(await scalar('select count(*)::int as v from public.ea_class_help_queue()'),0,'definer help queue cannot expose managed help');eq(await scalar('select count(*)::int as v from public.ea_class_attendance_rows($1)',['room:'+session.room_id]),0,'definer attendance RPC cannot expose managed roster');
await actor('staff');eq(await scalar('select count(*)::int as v from public.ea_class_help_queue()'),1,'assigned instructor receives own classroom help without OPIL role');
eq((await db.query('select name,email from public.ea_class_help_queue()')).rows,[{name:'student',email:''}],'managed help names use campus directory without exposing Auth email');
eq((await db.query('select name from public.ea_class_attendance_rows($1)',['room:'+session.room_id])).rows,[{name:'student'}],'managed attendance reports campus names');
await actor('student');eq(await scalar('select public.ea_class_help_may_ask($1) as v',['room:'+session.room_id]),true,'active classroom member may request in-room help');eq((await db.query('select name from public.ea_class_names($1)',['room:'+session.room_id])).rows,[{name:'student'}],'classroom participant names use campus directory');
await actor('other');eq(await scalar('select public.ea_class_help_may_ask($1) as v',['room:'+session.room_id]),false,'wrong cohort cannot create classroom help');eq(await scalar('select count(*)::int as v from public.ea_class_names($1)',['room:'+session.room_id]),0,'wrong cohort cannot read classroom participant names');
await actor('staff');await reject(()=>command('saveCohort',{id:a,title:'Cohort A',status:'archived'}),/End the live/,'live cohort cannot be archived before ending call');await reject(()=>command('saveClassSession',{...schedule,id:as,cohort_id:a,status:'cancelled'}),/End the live/,'live session cannot be cancelled before ending call');
await command('setCohortMember',{cohort_id:a,user_id:ids.student,active:false});await actor('student');eq((await access(session.room_slug)).can_join,false,'cohort removal immediately denies new join');eq(await scalar('select public.ea_room_in_session($1) as v',[session.room_id]),false,'past attendance does not bypass removed membership');eq(await scalar('select public.ea_room_reader($1) as v',['room:'+session.room_id]),false,'revoked member cannot read prior session records');
await actor('staff');await command('setCohortMember',{cohort_id:a,user_id:ids.student,active:true});
await owner('update public.ea_rooms set is_live=false where id=$1',[session.room_id]);
const replay=(await owner("insert into public.ea_room_replays(room_id,meeting_id,status,watch_url,published) values($1,'meeting','ready','https://example.test/replay',false) returning id",[session.room_id])).rows[0].id;
await actor('student');eq((await state()).class_sessions.find(x=>x.id===as).recording_url,null,'draft replay URL never returned to student');
await actor('staff');await db.query('select public.ea_room_publish_replay($1,true)',[replay]);
await actor('student');eq((await state()).class_sessions.find(x=>x.id===as).recording_url,'https://example.test/replay','published replay available to active cohort');
eq(await scalar('select public.ea_room_reader($1) as v',['room:'+session2.room_id]),false,'published replay does not open another session record');
await actor('other');eq(await scalar('select public.ea_room_reader($1) as v',['room:'+session.room_id]),false,'published replay never opens another cohort');
await actor('staff');await command('setCohortMember',{cohort_id:a,user_id:ids.other,active:true});
await actor('other');eq(await scalar('select public.ea_room_reader($1) as v',['room:'+session.room_id]),true,'new current cohort member may review missed published class without false attendance');eq((await state()).session_attendance.length,0,'missed-class replay access does not fabricate attendance');
await owner("insert into public.ea_rooms(slug,title,open_door) values('academy','Academy',false),('ht','Legacy HT',true)");await actor('legacy');eq((await scalar("select public.ea_room_state(null,'academy') as v")).is_host,true,'legacy Academy host behavior preserved');eq(await scalar("select public.ea_class_is_host('opil:7') as v"),true,'legacy OPIL facilitator behavior preserved');
await actor('outsider');eq((await scalar("select public.ea_room_state(null,'ht') as v")).can_join,true,'legacy HT compatibility room open door preserved');eq((await access(session.room_slug)).can_join,false,'legacy compatibility does not open managed classroom');
await owner('update public.ht_members set active=false where user_id=$1',[ids.student]);await actor('student');eq((await access(session.room_slug)).can_join,false,'inactive HT membership overrides retained cohort roster');
await owner('update public.ht_members set active=true where user_id=$1',[ids.student]);
await actor('instructor2');await reject(()=>command('saveClassSession',{...schedule,id:as,cohort_id:a}),/do not manage/,'another instructor cannot edit classroom session');
await actor('staff');await reject(()=>command('saveClassSession',{...schedule,id:as,cohort_id:a,starts_at:new Date(Date.now()+86400000).toISOString(),ends_at:new Date(Date.now()+90000000).toISOString()}),/dates are locked/,'meeting history prevents date reuse');
await reject(()=>command('saveClassSession',{...schedule,id:as,audience:'campus'}),/cannot change/,'session cannot be moved into campus audience');
const beforeRoomCount=await scalar('select count(*)::int as v from public.ea_rooms');await command('saveClassSession',{...schedule,id:as,cohort_id:a});eq(await scalar('select count(*)::int as v from public.ea_rooms'),beforeRoomCount,'resubmitting a session does not allocate another room');
await actor('anon');await reject(()=>access(session.room_slug),/permission denied/,'anonymous bridge execution denied');eq((await scalar('select public.ea_room_state(null,$1) as v',[session.room_slug])).can_join,false,'anonymous managed room state fails closed');
console.log(`Passed ${checks} classroom database checks. No remote database was modified.`);await db.close();
