import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const source=await readFile(new URL('../../ht/hub/campus-store.js',import.meta.url),'utf8');
const {createCampusStore}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const values=new Map(),storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},now=Date.now();
const options={storage,now:()=>now},student=createCampusStore({...options,demoRole:'student'}),staff=createCampusStore({...options,demoRole:'staff'}),leadership=createCampusStore({...options,demoRole:'leadership'});
let checks=0;const eq=(a,b,msg)=>{assert.deepEqual(a,b,msg);console.log(`ok ${++checks} - ${msg}`);},reject=async(fn,re,msg)=>{await assert.rejects(fn,re,msg);console.log(`ok ${++checks} - ${msg}`);};
let s=await student.load(),teacher=await staff.load();
const cohort=s.cohorts[0],session=s.class_sessions.find(x=>x.cohort_id===cohort.id),uid=s.user.id,secondCohort='a0000000-0000-4000-8000-000000000002',secondSession='b0000000-0000-4000-8000-000000000002';
eq(s.cohorts.length,1,'student demo returns assigned cohort only');eq(s.cohort_members.length,1,'student sees only own roster membership');eq(s.class_sessions.length,4,'student sees own sessions and separate campus gathering');
eq(teacher.members.some(m=>m.display_name==='Riley S.'&&m.role==='staff'),true,'demo directory includes separate instructor');eq(teacher.cohorts.length,1,'staff demo excludes another instructor cohort');
eq((await leadership.load()).cohorts.length,0,'leadership role does not reveal private classrooms');eq((await leadership.load()).class_sessions.every(x=>x.audience==='campus'),true,'leadership can view campus sessions');
eq(new Set(s.class_sessions.map(x=>x.room_id)).size,s.class_sessions.length,'demo sessions have unique room identities');eq(s.class_sessions.every(x=>/^htc-[a-f0-9]{24}$/.test(x.room_slug)),true,'sample slugs follow managed room contract');eq(s.class_sessions.some(x=>x.is_live),false,'sample schedule never implies real live conferencing');
await reject(()=>student.command('saveCohort',{title:'Self-created'}),/Staff access/,'student cannot self-create classrooms');
await reject(()=>staff.command('setCohortMember',{cohort_id:secondCohort,user_id:uid}),/do not manage/,'staff cannot manage other instructor roster');
await reject(()=>staff.command('saveClassSession',{id:secondSession}),/do not manage/,'staff cannot edit other instructor session');
await reject(()=>student.command('demoJoinSession',{session_id:secondSession}),/not available/,'wrong cohort rehearsal denied');
eq((await student.load()).session_attendance.length,0,'opening a session does not fabricate attendance');
await student.command('demoJoinSession',{session_id:session.id});await student.command('demoJoinSession',{session_id:session.id});
eq((await student.load()).session_attendance[0].joins,1,'repeated rehearsal join while joined is idempotent');eq((await staff.load()).session_attendance[0].session_id,session.id,'rehearsal attendance belongs to exact session');
eq((await leadership.load()).session_attendance.length,0,'leadership cannot see individual rehearsal attendance');
await student.command('demoLeaveSession',{session_id:session.id});await student.command('demoJoinSession',{session_id:session.id});eq((await student.load()).session_attendance[0].joins,2,'leaving and returning increments rehearsal join count');
const sessionPayload={...session};await reject(()=>staff.command('saveClassSession',{...sessionPayload,starts_at:new Date(now+86400000).toISOString(),ends_at:new Date(now+90000000).toISOString()}),/dates are locked/,'used session dates cannot be repurposed');
await reject(()=>staff.command('saveClassSession',{...sessionPayload,audience:'campus',cohort_id:null}),/cannot change/,'session audience identity cannot be reassigned');
await staff.command('setCohortMember',{cohort_id:cohort.id,user_id:uid,active:false});s=await student.load();eq(s.cohorts.length,0,'roster removal removes student classroom');eq(s.session_attendance.length,0,'removed member cannot read classroom attendance');await reject(()=>student.command('demoJoinSession',{session_id:session.id}),/not available/,'roster removal denies existing rehearsal link');
await staff.command('setCohortMember',{cohort_id:cohort.id,user_id:uid,active:true});
const created=(await staff.command('saveCohort',{title:'New cohort',description:'Student-led projects',status:'active'})).id;
const create={cohort_id:created,title:'First meeting',audience:'cohort',starts_at:new Date(now+600000).toISOString(),ends_at:new Date(now+3600000).toISOString(),status:'scheduled'};
const newSession=(await staff.command('saveClassSession',create)).id;
eq((await student.load()).cohorts.some(x=>x.id===created),false,'course enrollment does not imply new cohort roster membership');
await staff.command('setCohortMember',{cohort_id:created,user_id:uid,active:true});eq((await student.load()).class_sessions.some(x=>x.id===newSession),true,'assigned member sees newly scheduled session');
const prior=(await staff.load()).class_sessions.find(x=>x.id===newSession);await staff.command('saveClassSession',{...create,id:newSession,title:'Renamed meeting'});eq((await staff.load()).class_sessions.find(x=>x.id===newSession).room_id,prior.room_id,'session edits preserve unique room identity');
await reject(()=>staff.command('saveClassSession',{...create,title:'x'.repeat(121)}),/120 characters/,'demo session title matches legacy room title constraint');
await staff.command('saveClassSession',{...create,id:newSession,status:'cancelled'});await reject(()=>student.command('demoJoinSession',{session_id:newSession}),/not available/,'cancelled rehearsal cannot be joined');
await staff.command('saveClassSession',{...create,id:newSession,status:'scheduled'});await staff.command('saveCohort',{id:created,title:'New cohort',status:'archived'});await reject(()=>student.command('demoJoinSession',{session_id:newSession}),/not available/,'archived cohort cannot be joined');
const restored=createCampusStore({...options,demoRole:'student'});eq((await restored.load()).session_attendance.find(a=>a.session_id===session.id).joins,2,'classroom sample changes persist across store recreation');
eq(values.has('ht-campus-demo-v2'),true,'upgraded sample uses isolated v2 storage');
let liveCalls=[];const live=createCampusStore({client:{auth:{getSession:async()=>({data:{session:{user:{id:'real-member'}}}})},rpc:async(name,payload)=>{liveCalls.push([name,payload]);return name==='ht_campus_state'?{data:{member:{role:'staff'},cohorts:[{id:'real'}],class_sessions:[]}}:{data:{ok:true,id:'real-session'}};}}});eq((await live.load()).cohorts[0].id,'real','live store retains persisted classroom records');await live.command('saveClassSession',create);eq(liveCalls.at(-1),['ht_campus_command',{p_name:'saveClassSession',p_payload:create}],'live classroom scheduling uses validated RPC');
for(const store of [student,staff,leadership,restored,live])store.destroy();
console.log(`Passed ${checks} classroom store checks. No remote database was modified.`);
