-- Minimal legacy fixture, not a deployable schema. Real helper bodies are loaded from repository migrations by classrooms.test.mjs.
create schema storage;
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner_id text);
alter table storage.objects enable row level security;
grant usage on schema storage to authenticated;
grant select,insert,update,delete on storage.objects to authenticated;
create function public.ea_is_admin() returns boolean language sql stable as $$select auth.uid()='10000000-0000-4000-8000-000000000099'::uuid$$;
create function public.ea_is_member() returns boolean language sql stable as $$select auth.uid() is not null$$;
create function public.ea_jwt_email() returns text language sql stable security definer as $$select email from auth.users where id=auth.uid()$$;
create function public.ea_opil_is_program_team(p_user uuid) returns boolean language sql stable as $$select public.ea_is_admin()$$;
create function public.ea_opil_is_session_host(p_no integer) returns boolean language sql stable as $$select public.ea_is_admin()$$;
create function public.ea_opil_my_registration_status() returns text language sql stable as $$select 'none'::text$$;
create function public.ea_opil_in_cohort() returns boolean language sql stable as $$select public.ea_is_admin()$$;
create function public.ea_room_new_key() returns text language sql volatile as $$select replace(gen_random_uuid()::text,'-','')$$;
create table public.ea_rooms(id uuid primary key default gen_random_uuid(),title text not null default 'Room',slug text unique not null check(slug ~ '^[a-z][a-z0-9-]{1,31}$'),host_name text not null default 'Host',host_emails text[] not null default '{}',host_preset text default 'ht-class-host',guest_preset text default 'ht-class-guest',link_key text unique default public.ea_room_new_key(),open_door boolean not null default false,is_live boolean not null default false,live_since timestamptz,ended_at timestamptz,meeting_id text,max_participants integer default 50,recording_url text,warmup_q text,next_title text,next_at timestamptz,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.ea_room_members(room_id uuid references public.ea_rooms,user_id uuid references auth.users,first_joined_at timestamptz default now(),last_joined_at timestamptz default now(),joins integer default 1,primary key(room_id,user_id));
create table public.ea_room_hands(id uuid primary key default gen_random_uuid(),room_id uuid,user_id uuid,note text);
create table public.ea_room_replays(id uuid primary key default gen_random_uuid(),room_id uuid references public.ea_rooms,meeting_id text,status text,watch_url text,published boolean default false,duration_s integer,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.ea_class_events(id uuid primary key default gen_random_uuid(),room_key text,user_id uuid,body text);
create table public.ea_class_summaries(room_key text primary key,body text);
create table public.ea_class_transcripts(id uuid primary key default gen_random_uuid(),room_key text,body text);
create table public.ea_class_presence(room_key text,user_id uuid,state text,first_seen timestamptz,last_seen timestamptz,seconds integer,waited_s integer);
create table public.ea_class_board_ops(id uuid primary key default gen_random_uuid(),room_key text,user_id uuid,body text);
create table public.ea_class_warmups(id uuid primary key default gen_random_uuid(),room_key text,user_id uuid,body text);
create table public.ea_class_scores(id uuid primary key default gen_random_uuid(),room_key text,judge_id uuid,body text);
create table public.ea_class_help(id uuid primary key default gen_random_uuid(),room_key text,user_id uuid,track text,text text,status text,claimed_by uuid,claimed_name text,answer text,pinged_at timestamptz,answered_at timestamptz,answer_sent_at timestamptz,created_at timestamptz,updated_at timestamptz);
create table public.ea_class_reminders(room_key text,kind text);
create table public.ea_opil_materials(id uuid primary key default gen_random_uuid(),room_key text,uploaded_by uuid,file_path text,body text);
create table public.ea_opil_team_members(team_id uuid,user_id uuid);
create table public.ea_opil_teams(id uuid,name text,school text,is_staff boolean,created_at timestamptz);
create table public.ea_profiles(user_id uuid,display_name text);
create table public.ea_opil_registrations(email text,full_name text,school text);
create function public.ea_class_key_kind(p_key text) returns text language sql immutable as $$select split_part(p_key,':',1)$$;
create function public.ea_class_key_id(p_key text) returns text language sql immutable as $$select split_part(p_key,':',2)$$;
create function public.ea_class_person_name(p_uid uuid) returns text language sql stable as $$select 'A member'::text$$;
create policy legacy_storage on storage.objects for all to authenticated using(public.ea_is_admin()) with check(public.ea_is_admin());
