import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
let checks=0;
const eq=(a,b,message)=>{assert.deepEqual(a,b,message);console.log(`ok ${++checks} - ${message}`);};
const reject=async(fn,pattern,message)=>{await assert.rejects(fn,pattern,message);console.log(`ok ${++checks} - ${message}`);};
const ids={student:'10000000-0000-4000-8000-000000000001',staff:'10000000-0000-4000-8000-000000000002',leadership:'10000000-0000-4000-8000-000000000003',other:'10000000-0000-4000-8000-000000000004',outsider:'10000000-0000-4000-8000-000000000005',admin:'10000000-0000-4000-8000-000000000006'};
await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key,email text); create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; grant usage on schema auth, public to authenticated,anon; grant execute on function auth.uid() to authenticated,anon;`);
await db.exec(await readFile(new URL('../../supabase/migrations/20260921180637_ht_campus_hub.sql',import.meta.url),'utf8'));
console.log(`ok ${++checks} - additive migration executes successfully in PostgreSQL`);
for(const [role,id] of Object.entries(ids)){
 await db.query('insert into auth.users(id,email) values($1,$2)',[id,`${role}@example.test`]);
 if(role!=='outsider')await db.query('insert into public.ht_members(user_id,display_name,role) values($1,$2,$3)',[id,role,role==='other'?'student':role]);
}
async function actor(role){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[ids[role]||'']);await db.exec(`set role ${role==='anon'?'anon':'authenticated'}`);}
async function cmd(name,p={}){return (await db.query('select public.ht_campus_command($1,$2::jsonb) as result',[name,JSON.stringify(p)])).rows[0].result;}
async function state(){return (await db.query('select public.ht_campus_state() as result')).rows[0].result;}
async function count(table){return Number((await db.query(`select count(*) as n from public.${table}`)).rows[0].n);}
await actor('anon');
await reject(()=>state(),/permission denied/,'anonymous state access denied');
await reject(()=>cmd('post',{channel:'Campus',body:'No'}),/permission denied/,'anonymous command execution denied');
await reject(()=>db.query('select * from public.ht_members'),/permission denied/,'anonymous direct table access denied');
await actor('outsider');
await reject(()=>state(),/membership/,'Academy user without campus membership denied');
await reject(()=>cmd('setMember',{user_id:ids.outsider,display_name:'Outside',role:'admin'}),/membership/,'nonmember cannot provision membership');
eq(await count('ht_members'),0,'nonmember directory is empty under RLS');
await actor('staff');
const course=(await cmd('saveCourse',{title:'Test pathway',description:'Verify integrity',category:'Learning',status:'draft'})).id;
await reject(()=>cmd('saveCourse',{id:course,title:'Test pathway',status:'published'}),/add an activity/,'empty course cannot publish');
const first=(await cmd('saveModule',{course_id:course,title:'Knowledge',body:'Check the facts.',position:1,question:'What should you do?',options:['Trust everything','Verify it'],answer_index:1})).id;
const final=(await cmd('saveModule',{course_id:course,title:'Application',body:'Apply what you learned.',position:2,assignment_prompt:'Submit your work.'})).id;
await cmd('saveCourse',{id:course,title:'Test pathway',status:'published'});
const event=(await cmd('saveEvent',{title:'Workshop',starts_at:new Date(Date.now()-60000).toISOString(),ends_at:new Date(Date.now()+3600000).toISOString(),status:'published',capacity:1,checkin_code:'PRIVATECODE'})).id;
await cmd('saveAnnouncement',{title:'Campus notice',body:'Available now.',office:'Campus',status:'published',audience:'campus'});
await cmd('saveAnnouncement',{title:'Staff notice',body:'Staff only.',status:'published',audience:'staff'});
await cmd('saveAnnouncement',{title:'Draft notice',body:'Not published.',status:'draft',audience:'campus'});
await cmd('saveAnnouncement',{title:'Future notice',body:'Not due.',status:'published',audience:'campus',publish_at:'2099-01-01T00:00:00Z'});
await cmd('saveSettings',{ada_video_url:'https://example.test/ada.mp4',ada_video_poster:'https://example.test/poster.jpg',ada_video_transcript:'Transcript',support_email:'support@example.test'});
eq((await state()).modules.find(m=>m.id===first).answer_index,1,'staff state receives answer keys for editing');
await actor('student');
let s=await state();eq(s.modules.some(m=>Object.hasOwn(m,'answer_index')),false,'student state never contains answer keys');
await reject(()=>db.query('select ht_private.finish_course($1,$2)',[course,ids.student]),/permission denied/,'student cannot invoke internal credential helper');
await reject(()=>db.query('select ht_private.notify($1,$2,$3,$4)',[ids.other,'Forged notice','No','/ht/hub/']),/permission denied/,'student cannot invoke internal notification helper');
eq(s.events.some(e=>Object.hasOwn(e,'checkin_code')),false,'public events do not contain check-in codes');
eq(s.announcements.map(a=>a.title),['Campus notice'],'scheduled, draft and staff-only announcements hidden');
eq(s.metrics,null,'student cannot read institutional metrics');
await reject(()=>db.query('select * from ht_private.answer_keys'),/permission denied/,'student cannot directly read answer key table');
await reject(()=>db.query('select * from ht_private.event_codes'),/permission denied/,'student cannot directly read check-in code table');
await reject(()=>cmd('saveAnnouncement',{title:'Spoof',body:'No',status:'published',role:'admin'}),/Staff access/,'student cannot author even with a forged role payload');
await reject(()=>cmd('setMember',{user_id:ids.student,display_name:'Student',role:'admin'}),/Administrator access/,'student cannot self-promote');
await reject(()=>db.query("update public.ht_members set role='admin' where user_id=$1",[ids.student]),/permission denied/,'direct role escalation denied');
await reject(()=>db.query('insert into public.ht_progress(module_id,user_id) values($1,$2)',[first,ids.student]),/permission denied/,'direct completion insertion denied');
await reject(()=>cmd('completeModule',{module_id:first,answer_index:1}),/Enroll/,'completion requires enrollment');
await cmd('enroll',{course_id:course});await cmd('enroll',{course_id:course});
eq((await state()).enrollments.length,1,'enrollment is idempotent');
await reject(()=>cmd('submitWork',{module_id:final,body:'Skip ahead'}),/earlier/,'assignment cannot skip earlier modules');
await reject(()=>cmd('completeModule',{module_id:first,answer_index:0}),/knowledge check/,'incorrect answer rejected by server');
await reject(()=>cmd('completeModule',{module_id:first}),/knowledge check/,'missing answer rejected by server');
await cmd('completeModule',{module_id:first,answer_index:1});
await cmd('completeModule',{module_id:final});
eq((await state()).progress.length,1,'assignment self-completion cannot bypass staff review');
eq((await state()).enrollments[0].credential_id,null,'no premature credential');
await cmd('submitWork',{module_id:final,body:'My purpose, prompt, evidence and reflection.'});
const submission=(await state()).submissions[0];
await reject(()=>cmd('reviewWork',{id:submission.id,status:'approved',feedback:'Self approved'}),/Staff access/,'student cannot approve own work');
await reject(()=>cmd('checkin',{event_id:event,code:'PRIVATECODE'}),/RSVP/,'check-in requires RSVP');
await cmd('rsvp',{event_id:event,status:'going'});
await reject(()=>cmd('checkin',{event_id:event,code:'WRONG'}),/not correct/,'incorrect check-in code rejected');
await cmd('checkin',{event_id:event,code:'privatecode'});await cmd('checkin',{event_id:event,code:'PRIVATECODE'});
eq((await state()).attendance.length,1,'valid check-in persists exactly once');
const request=(await cmd('createRequest',{category:'Career',subject:'Private help',body:'Private request body'})).id;
await cmd('replyRequest',{request_id:request,body:'More context'});
await cmd('sendMessage',{recipient_id:ids.other,body:'Private campus message'});
const post=(await cmd('post',{channel:'Campus',body:'A campus discussion'})).id;
await cmd('like',{post_id:post,liked:true});await cmd('like',{post_id:post,liked:true});
eq((await state()).likes.length,1,'likes are idempotent');
await actor('other');
eq((await state()).requests.length,0,'another student cannot see support request');
eq((await state()).submissions.length,0,'another student cannot see submitted work');
eq((await state()).enrollments.length,0,'another student cannot see enrollment');
eq((await state()).attendance.length,0,'another student cannot see attendance');
eq((await state()).messages.length,1,'message recipient can read the message');
await reject(()=>cmd('replyRequest',{request_id:request,body:'Intrusion'}),/not available/,'another student cannot reply to private request');
await reject(()=>cmd('rsvp',{event_id:event,status:'going'}),/full/,'event capacity enforced');
await actor('leadership');
s=await state();eq([s.requests.length,s.responses.length,s.submissions.length,s.enrollments.length,s.attendance.length,s.messages.length],[0,0,0,0,0,0],'leadership gets no individual private records from other users');
eq(s.metrics.open_requests,1,'leadership receives aggregate support count');
eq(s.metrics.checkins,1,'leadership receives aggregate attendance count');
await reject(()=>cmd('updateRequest',{id:request,status:'resolved'}),/Staff access/,'leadership alone cannot administer private cases');
await actor('staff');
eq((await state()).messages.length,0,'staff cannot read other peoples direct messages');
await reject(()=>cmd('saveModule',{id:first,course_id:course,title:'Changed',body:'Changed',position:1}),/locked/,'module requirements locked after enrollment');
await cmd('reviewWork',{id:submission.id,status:'approved',feedback:'You met each requirement.'});
await cmd('updateRequest',{id:request,status:'in_progress',assigned_to:ids.staff});
await cmd('replyRequest',{request_id:request,body:'We can help.'});
await cmd('reply',{post_id:post,body:'Thanks for sharing.'});
await actor('student');
s=await state();assert.match(s.enrollments[0].credential_id,/^[0-9a-f-]{36}$/);console.log(`ok ${++checks} - all requirements produce a server-generated credential`);
eq(s.enrollments[0].completed_at!==null,true,'approval records completion time');
eq(s.requests[0].assigned_to,ids.staff,'staff ownership is visible to requesting student');
eq(s.responses.length,2,'support responses persist');
eq(s.notifications.some(n=>n.title==='Feedback on your work'),true,'review generates student notification');
await cmd('readNotification',{id:s.notifications[0].id});eq((await state()).notifications.find(n=>n.id===s.notifications[0].id).read_at!==null,true,'notification marked read for its owner');
await cmd('undoCheckin',{event_id:event});eq((await state()).attendance.length,0,'student can undo own check-in');
await actor('staff');
await cmd('reviewWork',{id:submission.id,status:'revision',feedback:'Please expand your reflection.'});
const futureEvent=(await cmd('saveEvent',{title:'Future workshop',starts_at:'2099-01-01T10:00:00Z',ends_at:'2099-01-01T11:00:00Z',status:'published',checkin_code:'FUTURE'})).id;
await actor('student');
eq((await state()).enrollments[0].credential_id,null,'withdrawing approval revokes credential');
await cmd('rsvp',{event_id:futureEvent,status:'going'});
await reject(()=>cmd('checkin',{event_id:futureEvent,code:'FUTURE'}),/30 minutes/,'check-in time window enforced');
await actor('admin');
await cmd('setMember',{user_id:ids.outsider,display_name:'New member',role:'student'});
await actor('outsider');eq((await state()).member.role,'student','administrator can provision an existing authenticated account');
await actor('admin');await cmd('setMember',{user_id:ids.outsider,display_name:'New member',role:'student',active:false});
await actor('outsider');await reject(()=>cmd('post',{channel:'Campus',body:'Removed user'}),/membership/,'membership revocation applies immediately');
await actor('staff');
const dependentCourse=(await cmd('saveCourse',{title:'Dependent review pathway',status:'draft'})).id;
const dependentFirst=(await cmd('saveModule',{course_id:dependentCourse,title:'First project',body:'Create it.',position:1,assignment_prompt:'Submit the first project.'})).id;
const dependentLast=(await cmd('saveModule',{course_id:dependentCourse,title:'Follow-on project',body:'Build on it.',position:2,assignment_prompt:'Submit the follow-on project.'})).id;
await cmd('saveCourse',{id:dependentCourse,title:'Dependent review pathway',status:'published'});
await actor('other');await cmd('enroll',{course_id:dependentCourse});await cmd('submitWork',{module_id:dependentFirst,body:'My first project.'});
const firstWork=(await state()).submissions.find(x=>x.module_id===dependentFirst).id;
await actor('staff');await cmd('reviewWork',{id:firstWork,status:'approved',feedback:'First approved.'});
await actor('other');await cmd('submitWork',{module_id:dependentLast,body:'My follow-on project.'});
const lastWork=(await state()).submissions.find(x=>x.module_id===dependentLast).id;
await actor('staff');await cmd('reviewWork',{id:lastWork,status:'approved',feedback:'Follow-on approved.'});
await cmd('reviewWork',{id:firstWork,status:'revision',feedback:'Revise your earlier assumptions.'});
await actor('other');eq((await state()).submissions.find(x=>x.id===lastWork).status,'revision','withdrawn approval invalidates dependent submission');
await reject(()=>cmd('submitWork',{module_id:dependentLast,body:'Retry too early.'}),/earlier/,'dependent work must wait for earlier revision');
await cmd('submitWork',{module_id:dependentFirst,body:'Revised first project.'});
await actor('staff');await cmd('reviewWork',{id:firstWork,status:'approved',feedback:'Revision approved.'});
await actor('other');await cmd('submitWork',{module_id:dependentLast,body:'Revised follow-on project.'});
eq((await state()).submissions.find(x=>x.id===lastWork).status,'submitted','dependent work can be resubmitted after recovery');
const seed=await readFile(new URL('../../supabase/seeds/ht-campus-ai-literacy.sql',import.meta.url),'utf8');
await reject(()=>db.exec(seed),/administrator/,'real-content seed rejects student');
await actor('admin');const beforeSeed=(await state()).members.length;await db.exec(seed);await db.exec(seed);
s=await state();eq(s.courses.filter(c=>c.id==='20000000-0000-4000-8000-000000000001').length,1,'real-content seed is idempotent');
eq(s.modules.filter(m=>m.course_id==='20000000-0000-4000-8000-000000000001').length,3,'real-content seed creates complete AI Literacy curriculum');
eq(s.members.length,beforeSeed,'real-content seed creates no fictional users');
await db.exec('reset role');
const tables=(await db.query("select tablename,rowsecurity from pg_tables where schemaname='public' and tablename like 'ht_%'")).rows;
eq(tables.every(t=>t.rowsecurity),true,'RLS enabled on every public campus table');
for(const table of tables){eq((await db.query("select has_table_privilege('authenticated',$1,'INSERT,UPDATE,DELETE') as allowed",[`public.${table.tablename}`])).rows[0].allowed,false,`${table.tablename}: direct mutation grants absent`);}
console.log(`Passed ${checks} database checks. No remote database was modified.`);
await db.close();
