import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const source=await readFile(new URL('../../ht/hub/campus-store.js',import.meta.url),'utf8');
const {createCampusStore}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const values=new Map();const storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)};
const time=Date.now(),opts={storage,now:()=>time};
const student=createCampusStore({...opts,demoRole:'student'}),staff=createCampusStore({...opts,demoRole:'staff'}),leadership=createCampusStore({...opts,demoRole:'leadership'});
let checks=0;const eq=(a,b,msg)=>{assert.deepEqual(a,b,msg);console.log(`ok ${++checks} - ${msg}`);};const reject=async(fn,re,msg)=>{await assert.rejects(fn,re,msg);console.log(`ok ${++checks} - ${msg}`);};
let s=await student.load();eq(s.mode,'demo','explicit student selection opens demo');eq(s.member.role,'student','demo identity is student');
const course=s.courses[0],modules=s.modules.filter(m=>m.course_id===course.id).sort((a,b)=>a.position-b.position),event=s.events[0];
await reject(()=>student.command('saveSettings',{}),/Staff access/,'student demo cannot author settings');
await reject(()=>student.command('completeModule',{module_id:modules[1].id,answer_index:modules[1].answer_index}),/earlier/,'demo honors lesson order');
await reject(()=>student.command('completeModule',{module_id:modules[0].id,answer_index:0}),/knowledge check/,'demo rejects wrong answer');
await reject(()=>student.command('checkin',{event_id:event.id,code:'HT2026'}),/RSVP/,'demo check-in requires RSVP');
await student.command('rsvp',{event_id:event.id,status:'going'});
await reject(()=>student.command('checkin',{event_id:event.id,code:'invalid'}),/not correct/,'demo check-in requires correct code');
await student.command('checkin',{event_id:event.id,code:'HT2026'});
eq((await staff.load()).attendance.length,1,'student check-in appears in staff data');
for(const m of modules.filter(m=>!m.assignment_prompt))await student.command('completeModule',{module_id:m.id,answer_index:m.answer_index});
await student.command('completeModule',{module_id:modules.at(-1).id});eq((await student.load()).enrollments[0].credential_id,null,'demo requires review for assignment completion');
await student.command('submitWork',{module_id:modules.at(-1).id,body:'My purpose, prompt, review, and reflection.'});
const submission=(await staff.load()).submissions.find(x=>x.user_id===s.user.id);
await staff.command('reviewWork',{id:submission.id,status:'approved',feedback:'Clear purpose and thoughtful review.'});
s=await student.load();eq(Boolean(s.enrollments.find(e=>e.course_id===course.id).credential_id),true,'staff approval generates demo credential');
eq((await leadership.load()).requests.length,0,'leadership demo excludes private requests');
eq((await leadership.load()).submissions.length,0,'leadership demo excludes student work');
eq((await leadership.load()).metrics.checkins,1,'leadership demo sees aggregate attendance');
const rid=(await student.command('createRequest',{category:'Technology',subject:'Help with audio',body:'I cannot hear the session.'})).id;
await staff.command('updateRequest',{id:rid,status:'in_progress',assigned_to:(await staff.load()).user.id});
await staff.command('replyRequest',{request_id:rid,body:'Please check your selected speaker.'});
s=await student.load();eq(s.responses.some(r=>r.request_id===rid),true,'support response persists across roles');
await student.command('sendMessage',{recipient_id:(await staff.load()).user.id,body:'Thank you for the help.'});eq((await staff.load()).messages.some(m=>m.body==='Thank you for the help.'),true,'private message reaches recipient');eq((await leadership.load()).messages.length,0,'leadership cannot read private messages');
await staff.command('saveAnnouncement',{title:'Visible campus notice',body:'Published by staff.',status:'published',audience:'campus'});eq((await student.load()).announcements.some(a=>a.title==='Visible campus notice'),true,'staff publishing appears for student');
await staff.command('saveAnnouncement',{title:'Future notice',body:'Not yet visible.',status:'published',audience:'campus',publish_at:'2099-01-01T00:00:00Z'});eq((await student.load()).announcements.some(a=>a.title==='Future notice'),false,'future announcements remain hidden');
const draft=(await staff.command('saveCourse',{title:'New pathway',description:'A staff-created pathway.',status:'draft'})).id;
await staff.command('saveModule',{course_id:draft,title:'First activity',body:'Read and reflect.',position:1});
await staff.command('saveCourse',{id:draft,title:'New pathway',description:'A staff-created pathway.',status:'published'});eq((await student.load()).courses.some(c=>c.id===draft),true,'staff can author and publish a complete course');
await student.command('enroll',{course_id:draft});await reject(()=>staff.command('saveModule',{course_id:draft,title:'Late activity',body:'Cannot change enrolled requirements.',position:2}),/locked/,'demo freezes enrolled course requirements');
const dependent=(await staff.command('saveCourse',{title:'Dependent demo',status:'draft'})).id;
const dep1=(await staff.command('saveModule',{course_id:dependent,title:'First project',body:'Create it.',position:1,assignment_prompt:'Share the first project.'})).id;
const dep2=(await staff.command('saveModule',{course_id:dependent,title:'Follow-on project',body:'Build on it.',position:2,assignment_prompt:'Share the follow-on project.'})).id;
await staff.command('saveCourse',{id:dependent,title:'Dependent demo',status:'published'});
await student.command('enroll',{course_id:dependent});await student.command('submitWork',{module_id:dep1,body:'First work.'});
const depWork1=(await student.load()).submissions.find(x=>x.module_id===dep1).id;
await staff.command('reviewWork',{id:depWork1,status:'approved',feedback:'Approved.'});
await student.command('submitWork',{module_id:dep2,body:'Follow-on work.'});
const depWork2=(await student.load()).submissions.find(x=>x.module_id===dep2).id;
await staff.command('reviewWork',{id:depWork2,status:'approved',feedback:'Approved.'});
await staff.command('reviewWork',{id:depWork1,status:'revision',feedback:'Revisit earlier work.'});
eq((await student.load()).submissions.find(x=>x.id===depWork2).status,'revision','demo invalidates downstream approved submission');
await student.command('submitWork',{module_id:dep1,body:'Revised earlier work.'});await staff.command('reviewWork',{id:depWork1,status:'approved',feedback:'Revision approved.'});
await student.command('submitWork',{module_id:dep2,body:'Revised follow-on work.'});
eq((await student.load()).submissions.find(x=>x.id===depWork2).status,'submitted','demo recovers dependent assignment without stale approval dead end');
const restored=createCampusStore({...opts,demoRole:'student'});eq((await restored.load()).attendance.length,1,'sample changes survive store recreation');
const guestClient={auth:{getSession:async()=>({data:{session:null},error:null})},rpc:()=>{throw Error('Guest must not call RPC');}};
const guest=createCampusStore({...opts,client:guestClient});eq((await guest.load()).mode,'guest','signed-out visitors get read-only illustration');await reject(()=>guest.command('post',{channel:'Campus',body:'No'}),/Sign in/,'guest cannot mutate');
let calls=[];const liveClient={auth:{getSession:async()=>({data:{session:{user:{id:'live-user',email:'member@example.test'}}},error:null})},rpc:async(name,payload)=>{calls.push([name,payload]);if(name==='ht_campus_state')return {data:{member:{user_id:'live-user',display_name:'Real Member',role:'student'},events:[]},error:null};return {data:{ok:true},error:null};}};
const live=createCampusStore({client:liveClient});eq((await live.load()).mode,'live','authenticated member uses live RPC');await live.command('rsvp',{event_id:'event-id',status:'going'});eq(calls.at(-1),['ht_campus_command',{p_name:'rsvp',p_payload:{event_id:'event-id',status:'going'}}],'live command dispatches exact RPC contract');
const unavailable=createCampusStore({client:{...liveClient,rpc:async()=>({data:null,error:{message:'function public.ht_campus_state does not exist'}})}});const failed=await unavailable.load();eq(failed.mode,'unavailable','missing migration remains unavailable');eq(failed.events.length,0,'missing migration never displays sample live events');await reject(()=>unavailable.command('rsvp',{}),/not been activated/,'missing backend cannot claim successful writes');
const nonmember=createCampusStore({client:{...liveClient,rpc:async()=>({data:null,error:{message:'Your account does not yet have an active HT Hub membership.'}})}});eq((await nonmember.load()).mode,'unavailable','nonmember not automatically promoted');
let emitted=0;const unsub=student.subscribe(()=>emitted++);await student.command('like',{post_id:(await student.load()).posts[0].id,liked:true});eq(emitted,1,'successful command notifies subscribers');unsub();
let authListener,resolveOld,markEntered,authSession={user:{id:'account-a',email:'a@example.test'}},rpcGate=true,authWrites=0;
let entered=new Promise(resolve=>{markEntered=resolve;});
let gate=new Promise(resolve=>{resolveOld=resolve;});
const authClient={auth:{getSession:async()=>({data:{session:authSession},error:null}),onAuthStateChange:fn=>{authListener=fn;return {data:{subscription:{unsubscribe(){}}}};}},rpc:async(name)=>{if(name==='ht_campus_command'){authWrites++;return {data:{ok:true},error:null};}if(rpcGate){markEntered();return gate;}return {data:{member:{user_id:authSession.user.id,role:'student',display_name:'Current account'},requests:[]},error:null};}};
const authStore=createCampusStore({client:authClient});const authEvents=[];authStore.subscribe(event=>authEvents.push(event));
const oldLoad=authStore.load();await entered;
authSession=null;authListener('SIGNED_OUT',null);
resolveOld({data:{member:{user_id:'account-a',role:'student',display_name:'Previous account'},requests:[{id:'private-a',body:'Private previous-account request'}]},error:null});
const oldResult=await oldLoad;eq(oldResult.user,null,'sign-out invalidates in-flight state identity');eq(oldResult.requests.length,0,'late old response cannot restore private records after sign-out');
eq(authEvents.at(-1),{reason:'auth',event:'SIGNED_OUT',user_id:null},'auth event reports sign-out identity');
await reject(()=>authStore.command('post',{channel:'Campus',body:'Should not write'}),/Sign in/,'late load cannot re-enable writes after sign-out');
eq((await authStore.load()).mode,'guest','subsequent signed-out load returns read-only guest');
rpcGate=false;authSession={user:{id:'account-a',email:'a@example.test'}};authListener('SIGNED_IN',authSession);await authStore.load();
const switchingWrite=authStore.command('post',{channel:'Campus',body:'Intended for prior account'});
authSession={user:{id:'account-b',email:'b@example.test'}};authListener('SIGNED_IN',authSession);
await reject(()=>switchingWrite,/account changed/,'account switch prevents deferred command dispatch as new user');eq(authWrites,0,'aborted account-switch command never reaches RPC');
await authStore.load();
rpcGate=true;entered=new Promise(resolve=>{markEntered=resolve;});gate=new Promise(resolve=>{resolveOld=resolve;});
const sameUserLoad=authStore.load();await entered;authListener('SIGNED_IN',authSession);
resolveOld({data:{member:{user_id:'account-b',display_name:'Current account',role:'student'},requests:[]},error:null});
eq((await sameUserLoad).user.id,'account-b','same-identity refocus does not invalidate an in-flight state load');
for(const store of [student,staff,leadership,restored,guest,live,unavailable,nonmember,authStore])store.destroy();
await reject(()=>student.command('post',{}),/session has ended/,'destroyed store prevents changes');
console.log(`Passed ${checks} store checks. No remote database was modified.`);
