import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { createRequire } from 'node:module';
const playwright=createRequire(new URL('../../tools/ht-campus-tests/package.json',import.meta.url))('playwright');
const source = await fs.readFile(new URL('../../ht/hub/campus-staff.js', import.meta.url), 'utf8');
const browser=await playwright.chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage();
page.setDefaultTimeout(10000);
const errors=[]; page.on('pageerror', error => errors.push(error.message));
const fixtures={mode:'demo',user:{id:'staff-1'},member:{user_id:'staff-1',display_name:'Morgan A.',role:'staff'},announcements:[{id:'notice-1',title:'<img src=x onerror=alert(1)>',body:'Keep <all> content as text',office:'Student Affairs',audience:'campus',status:'draft',created_at:'2026-09-21T10:00:00Z'}],events:[{id:'event-1',title:'Welcome workshop',description:'Learn together',office:'Student Affairs',location:'Library',starts_at:'2026-10-01T15:00:00Z',ends_at:'2026-10-01T16:00:00Z',status:'published',capacity:30}],courses:[{id:'course-1',title:'AI Literacy',description:'Practice responsible AI',category:'AI Literacy',status:'draft'}],modules:[{id:'module-1',course_id:'course-1',title:'First project',body:'Make a plan',position:1,question:null,options:[],assignment_prompt:'Submit a grounded response with sources.'}],submissions:[{id:'work-1',module_id:'module-1',user_id:'student-1',body:'Student evidence',link_url:'javascript:alert(1)',status:'submitted',submitted_at:'2026-09-21T10:00:00Z'}],requests:[{id:'case-1',user_id:'student-1',subject:'Learning help',body:'Need help with a lesson',category:'Learning',status:'open',created_at:'2026-09-21T10:00:00Z'},{id:'case-2',user_id:'student-2',subject:'Private other case',body:'Private information',category:'Technology',status:'open',created_at:'2026-09-21T10:00:00Z'}],responses:[],members:[{user_id:'staff-1',display_name:'Morgan A.',role:'staff'},{user_id:'student-1',display_name:'Jordan B.',role:'student'}],settings:{},metrics:{members:20,active_learners:10,enrollments:15,completions:3,rsvps:12,checkins:9,open_requests:2,unanswered_requests:2,announcements:1}};
try {
 await page.setContent('<div id="app"></div>');
 await page.evaluate(async ({source,fixtures}) => {
   const mod=await import(URL.createObjectURL(new Blob([source],{type:'text/javascript'})));
   window.calls=[]; window.notices=[]; window.success=true; window.failSlow=false;
   const ctx={state:fixtures,esc:value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),icon:()=>'',href:view=>`/ht/hub/${view}/?demo=staff`,formatDate:value=>new Date(value).toLocaleDateString(),formatTime:value=>new Date(value).toLocaleTimeString(),notify:(message,type)=>window.notices.push({message,type}),refresh:()=>{},run:async (...args)=>{window.calls.push(args);if(window.failSlow) await new Promise(resolve=>setTimeout(resolve,100));return window.success;}};
   window.ctx=ctx; window.mount=view=>{window.cleanup?.();document.querySelector('#app').innerHTML=mod.renderStaff(view,ctx);window.cleanup=mod.bindStaff(view,document.querySelector('#app'),ctx);};window.mount('staff');
 },{source,fixtures});
 assert.equal(await page.locator('[role=tab]').count(),5);
 assert.equal(await page.locator('img').count(),0,'untrusted title cannot become HTML');
 await page.getByRole('tab',{name:'Announcements',exact:true}).focus();
 await page.keyboard.press('ArrowRight');
 assert.equal(await page.getByRole('tab',{name:'Events',exact:true}).getAttribute('aria-selected'),'true');
 // Event authoring preserves data on failure and validates end dates.
 await page.getByLabel('Event title',{exact:true}).fill('New event');
 await page.getByLabel('Description',{exact:true}).fill('An accessible campus workshop');
 await page.getByLabel('Location',{exact:true}).fill('Library');
 await page.getByLabel('Starts (your local time)').fill('2026-10-02T12:00');
 await page.getByLabel('Ends (your local time)').fill('2026-10-02T11:00');
 await page.getByRole('button',{name:'Create event',exact:true}).click();
 assert.equal(await page.evaluate(()=>calls.length),0);
 assert.match(await page.evaluate(()=>notices.at(-1).message),/end time must be after/i);
 await page.getByLabel('Ends (your local time)').fill('2026-10-02T13:00');
 await page.getByLabel('Online join link (optional)').fill('http://example.edu/live');
 await page.getByRole('button',{name:'Create event',exact:true}).click();
 assert.equal(await page.evaluate(()=>calls.length),0);
 assert.match(await page.evaluate(()=>notices.at(-1).message),/https:\/\//);
 await page.getByLabel('Online join link (optional)').fill('https://example.edu/live');
 await page.locator('summary').filter({hasText:'Check-in code'}).click();
 assert.equal(await page.getByLabel('Check-in code (optional)',{exact:true}).getAttribute('maxlength'),'40');
 await page.getByLabel('Check-in code (optional)',{exact:true}).fill('WELCOME');
 await page.evaluate(()=>success=false);
 await page.getByRole('button',{name:'Create event',exact:true}).click();
 assert.equal(await page.getByLabel('Event title',{exact:true}).inputValue(),'New event');
 let call=await page.evaluate(()=>calls.at(-1));
 assert.equal(call[0],'saveEvent'); assert.equal(call[1].checkin_code,'WELCOME');
 await page.evaluate(()=>{success=true;failSlow=true;});
 await page.getByRole('button',{name:'Create event',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'Create event',exact:true}).isDisabled(),true);
 await page.waitForFunction(()=>!document.querySelector('button[type=submit]').disabled);
 // Announcement scheduling carries native local date as UTC and escaped content.
 await page.getByRole('tab',{name:'Announcements',exact:true}).click();
 await page.getByLabel('Title',{exact:true}).fill('Meet the campus team');
 await page.getByLabel('Message',{exact:true}).fill('Join us tomorrow.');
 await page.getByLabel('Publication',{exact:true}).selectOption('published');
 await page.getByLabel('Publish at (optional, your local time)').fill('2026-10-03T09:00');
 await page.getByRole('button',{name:'Save announcement',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('button[type=submit]').disabled);
 call=await page.evaluate(()=>calls.at(-1)); assert.equal(call[0],'saveAnnouncement');assert.equal(call[1].status,'published');assert.ok(call[1].publish_at.endsWith('Z'));
 // Course module checks reject an invalid answer and retain the form.
 await page.getByRole('tab',{name:'Learning',exact:true}).click();
 await page.getByRole('button',{name:'Edit AI Literacy',exact:true}).click();
 await page.getByLabel('Step title',{exact:true}).fill('Check sources');
 await page.getByLabel('Lesson content',{exact:true}).fill('Compare claims with primary sources.');
 await page.locator('summary').filter({hasText:'Knowledge check (optional)'}).click();
 await page.getByLabel('Question',{exact:true}).fill('What should you verify?');
 await page.getByLabel('Answer options').fill('The source\nThe color');
 await page.getByLabel('Correct answer number').fill('3');
 const before=await page.evaluate(()=>calls.length);
 await page.getByRole('button',{name:'Add learning step',exact:true}).click();
 assert.equal(await page.evaluate(()=>calls.length),before);
 assert.match(await page.evaluate(()=>notices.at(-1).message),/correct answer/i);
 await page.getByLabel('Correct answer number').fill('1');
 await page.getByRole('button',{name:'Add learning step',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('form[data-form=module] button[type=submit]').disabled);
 call=await page.evaluate(()=>calls.at(-1));assert.equal(call[0],'saveModule');assert.equal(call[1].answer_index,0);assert.equal(call[1].position,2);
 await page.evaluate(()=>{ctx.state.enrollments=[{course_id:'course-1',user_id:'student-1'}];mount('staff');});
 assert.equal(await page.getByLabel('Step title',{exact:true}).isDisabled(),true);
 assert.equal(await page.getByText(/Learning requirements are locked because students have enrolled/).count(),1);
 // Submission link protocols are constrained and review feedback is required.
 await page.getByRole('tab',{name:'Review work',exact:true}).click();
 assert.equal(await page.locator('a[href^="javascript:"]').count(),0);
 await page.getByLabel('Feedback for the student').fill('Please include a primary source.');
 await page.getByLabel('Review decision').selectOption('revision');
 await page.getByRole('button',{name:'Send review',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('button[type=submit]').disabled);
 call=await page.evaluate(()=>calls.at(-1));assert.equal(call[0],'reviewWork');assert.equal(call[1].status,'revision');
 // Settings accepts direct media URLs and readable transcript text.
 await page.getByRole('tab',{name:'Settings',exact:true}).click();
 await page.getByLabel('Ada video URL',{exact:true}).fill('https://example.edu/ada.mp4');
 await page.getByLabel('Video transcript',{exact:true}).fill('Welcome to HT.');
 await page.getByLabel('Support email',{exact:true}).fill('help@example.edu');
 await page.getByRole('button',{name:'Save settings',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('button[type=submit]').disabled);
 call=await page.evaluate(()=>calls.at(-1));assert.equal(call[0],'saveSettings');assert.equal(call[1].ada_video_transcript,'Welcome to HT.');
 // Staff supports a student, assigns the case and submits a response.
 await page.evaluate(()=>mount('support'));
 await page.getByRole('button').filter({hasText:'Learning help'}).click();
 await page.getByLabel('Staff owner').selectOption('staff-1');
 await page.getByLabel('Status',{exact:true}).selectOption('in_progress');
 await page.getByRole('button',{name:'Update request',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('form[data-form=request-status] button[type=submit]').disabled);
 call=await page.evaluate(()=>calls.at(-1));assert.equal(call[0],'updateRequest');assert.equal(call[1].assigned_to,'staff-1');
 await page.getByLabel('Reply',{exact:true}).fill('I can help. Which part was confusing?');
 await page.getByRole('button',{name:'Send reply',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('form[data-form=request-reply] button[type=submit]').disabled);
 call=await page.evaluate(()=>calls.at(-1));assert.equal(call[0],'replyRequest');assert.equal(call[1].request_id,'case-1');
 // Student sees own requests even when a fixture accidentally contains another case.
 await page.evaluate(()=>{ctx.state.user={id:'student-1'};ctx.state.member={user_id:'student-1',role:'student',display_name:'Jordan B.'};mount('support');});
 assert.equal(await page.getByText('Private other case',{exact:true}).count(),0);
 assert.equal(await page.getByRole('button').filter({hasText:'Learning help'}).count(),1);
 await page.getByLabel('Subject',{exact:true}).fill('A new question');
 await page.getByLabel('What do you need help with?').fill('Please explain the workshop location.');
 await page.getByRole('button',{name:'Send request',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('button[type=submit]').disabled);
 call=await page.evaluate(()=>calls.at(-1));assert.equal(call[0],'createRequest');
 await page.evaluate(()=>mount('staff'));
 assert.equal(await page.locator('form').count(),0);
 // Leadership never receives a private case queue and exports aggregates only.
 await page.evaluate(()=>{ctx.state.user={id:'leader-1'};ctx.state.member={user_id:'leader-1',role:'leadership'};mount('support');});
 assert.equal(await page.getByText('Learning help',{exact:true}).count(),0);
 await page.evaluate(()=>mount('insights'));
 assert.equal(await page.locator('.campus-metric').count(),9);
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export CSV',exact:true}).click();const download=await downloadPromise;
 const downloaded=await fs.readFile(await download.path(),'utf8');assert.match(downloaded,/Campus members/);assert.match(downloaded,/SAMPLE DATA/);assert.match(downloaded,/Generated at/);assert.ok(download.suggestedFilename().includes('SAMPLE'));assert.ok(!downloaded.includes('student-1'));assert.ok(!downloaded.includes('Private information'));
 await page.evaluate(()=>{ctx.state.mode='guest';ctx.state.user=null;ctx.state.member=null;mount('support');});
 assert.equal(await page.locator('form').count(),0);assert.equal(await page.getByRole('link',{name:'Sign in',exact:true}).count(),1);
 assert.deepEqual(errors,[]);
 console.log('PASS: staff authoring, scheduling, quiz validation, review, settings, request handling, role isolation, CSV privacy, keyboard tabs, escaping, and failed-save preservation.');
} finally { await browser.close(); }
